// Code generated by ent, DO NOT EDIT.

package unit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedBy, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCorrelationID, v))
}

// AgentGoalID applies equality check predicate on the "agent_goal_id" field. It's identical to AgentGoalIDEQ.
func AgentGoalID(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAgentGoalID, v))
}

// UnitNumber applies equality check predicate on the "unit_number" field. It's identical to UnitNumberEQ.
func UnitNumber(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUnitNumber, v))
}

// SquareFootage applies equality check predicate on the "square_footage" field. It's identical to SquareFootageEQ.
func SquareFootage(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSquareFootage, v))
}

// Bedrooms applies equality check predicate on the "bedrooms" field. It's identical to BedroomsEQ.
func Bedrooms(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldBedrooms, v))
}

// Bathrooms applies equality check predicate on the "bathrooms" field. It's identical to BathroomsEQ.
func Bathrooms(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldBathrooms, v))
}

// Floor applies equality check predicate on the "floor" field. It's identical to FloorEQ.
func Floor(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFloor, v))
}

// FloorPlan applies equality check predicate on the "floor_plan" field. It's identical to FloorPlanEQ.
func FloorPlan(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFloorPlan, v))
}

// AdaAccessible applies equality check predicate on the "ada_accessible" field. It's identical to AdaAccessibleEQ.
func AdaAccessible(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAdaAccessible, v))
}

// PetFriendly applies equality check predicate on the "pet_friendly" field. It's identical to PetFriendlyEQ.
func PetFriendly(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldPetFriendly, v))
}

// Furnished applies equality check predicate on the "furnished" field. It's identical to FurnishedEQ.
func Furnished(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFurnished, v))
}

// MarketRentAmountCents applies equality check predicate on the "market_rent_amount_cents" field. It's identical to MarketRentAmountCentsEQ.
func MarketRentAmountCents(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldMarketRentAmountCents, v))
}

// MarketRentCurrency applies equality check predicate on the "market_rent_currency" field. It's identical to MarketRentCurrencyEQ.
func MarketRentCurrency(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldMarketRentCurrency, v))
}

// AmiRestriction applies equality check predicate on the "ami_restriction" field. It's identical to AmiRestrictionEQ.
func AmiRestriction(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAmiRestriction, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldSource, vs...))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldCorrelationID, v))
}

// AgentGoalIDEQ applies the EQ predicate on the "agent_goal_id" field.
func AgentGoalIDEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAgentGoalID, v))
}

// AgentGoalIDNEQ applies the NEQ predicate on the "agent_goal_id" field.
func AgentGoalIDNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldAgentGoalID, v))
}

// AgentGoalIDIn applies the In predicate on the "agent_goal_id" field.
func AgentGoalIDIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDNotIn applies the NotIn predicate on the "agent_goal_id" field.
func AgentGoalIDNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDGT applies the GT predicate on the "agent_goal_id" field.
func AgentGoalIDGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldAgentGoalID, v))
}

// AgentGoalIDGTE applies the GTE predicate on the "agent_goal_id" field.
func AgentGoalIDGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldAgentGoalID, v))
}

// AgentGoalIDLT applies the LT predicate on the "agent_goal_id" field.
func AgentGoalIDLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldAgentGoalID, v))
}

// AgentGoalIDLTE applies the LTE predicate on the "agent_goal_id" field.
func AgentGoalIDLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldAgentGoalID, v))
}

// AgentGoalIDContains applies the Contains predicate on the "agent_goal_id" field.
func AgentGoalIDContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldAgentGoalID, v))
}

// AgentGoalIDHasPrefix applies the HasPrefix predicate on the "agent_goal_id" field.
func AgentGoalIDHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldAgentGoalID, v))
}

// AgentGoalIDHasSuffix applies the HasSuffix predicate on the "agent_goal_id" field.
func AgentGoalIDHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldAgentGoalID, v))
}

// AgentGoalIDIsNil applies the IsNil predicate on the "agent_goal_id" field.
func AgentGoalIDIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldAgentGoalID))
}

// AgentGoalIDNotNil applies the NotNil predicate on the "agent_goal_id" field.
func AgentGoalIDNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldAgentGoalID))
}

// AgentGoalIDEqualFold applies the EqualFold predicate on the "agent_goal_id" field.
func AgentGoalIDEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldAgentGoalID, v))
}

// AgentGoalIDContainsFold applies the ContainsFold predicate on the "agent_goal_id" field.
func AgentGoalIDContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldAgentGoalID, v))
}

// UnitNumberEQ applies the EQ predicate on the "unit_number" field.
func UnitNumberEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUnitNumber, v))
}

// UnitNumberNEQ applies the NEQ predicate on the "unit_number" field.
func UnitNumberNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUnitNumber, v))
}

// UnitNumberIn applies the In predicate on the "unit_number" field.
func UnitNumberIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUnitNumber, vs...))
}

// UnitNumberNotIn applies the NotIn predicate on the "unit_number" field.
func UnitNumberNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUnitNumber, vs...))
}

// UnitNumberGT applies the GT predicate on the "unit_number" field.
func UnitNumberGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldUnitNumber, v))
}

// UnitNumberGTE applies the GTE predicate on the "unit_number" field.
func UnitNumberGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldUnitNumber, v))
}

// UnitNumberLT applies the LT predicate on the "unit_number" field.
func UnitNumberLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldUnitNumber, v))
}

// UnitNumberLTE applies the LTE predicate on the "unit_number" field.
func UnitNumberLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldUnitNumber, v))
}

// UnitNumberContains applies the Contains predicate on the "unit_number" field.
func UnitNumberContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldUnitNumber, v))
}

// UnitNumberHasPrefix applies the HasPrefix predicate on the "unit_number" field.
func UnitNumberHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldUnitNumber, v))
}

// UnitNumberHasSuffix applies the HasSuffix predicate on the "unit_number" field.
func UnitNumberHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldUnitNumber, v))
}

// UnitNumberEqualFold applies the EqualFold predicate on the "unit_number" field.
func UnitNumberEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldUnitNumber, v))
}

// UnitNumberContainsFold applies the ContainsFold predicate on the "unit_number" field.
func UnitNumberContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldUnitNumber, v))
}

// UnitTypeEQ applies the EQ predicate on the "unit_type" field.
func UnitTypeEQ(v UnitType) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUnitType, v))
}

// UnitTypeNEQ applies the NEQ predicate on the "unit_type" field.
func UnitTypeNEQ(v UnitType) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUnitType, v))
}

// UnitTypeIn applies the In predicate on the "unit_type" field.
func UnitTypeIn(vs ...UnitType) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUnitType, vs...))
}

// UnitTypeNotIn applies the NotIn predicate on the "unit_type" field.
func UnitTypeNotIn(vs ...UnitType) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUnitType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldStatus, vs...))
}

// SquareFootageEQ applies the EQ predicate on the "square_footage" field.
func SquareFootageEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSquareFootage, v))
}

// SquareFootageNEQ applies the NEQ predicate on the "square_footage" field.
func SquareFootageNEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldSquareFootage, v))
}

// SquareFootageIn applies the In predicate on the "square_footage" field.
func SquareFootageIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldSquareFootage, vs...))
}

// SquareFootageNotIn applies the NotIn predicate on the "square_footage" field.
func SquareFootageNotIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldSquareFootage, vs...))
}

// SquareFootageGT applies the GT predicate on the "square_footage" field.
func SquareFootageGT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldSquareFootage, v))
}

// SquareFootageGTE applies the GTE predicate on the "square_footage" field.
func SquareFootageGTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldSquareFootage, v))
}

// SquareFootageLT applies the LT predicate on the "square_footage" field.
func SquareFootageLT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldSquareFootage, v))
}

// SquareFootageLTE applies the LTE predicate on the "square_footage" field.
func SquareFootageLTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldSquareFootage, v))
}

// BedroomsEQ applies the EQ predicate on the "bedrooms" field.
func BedroomsEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldBedrooms, v))
}

// BedroomsNEQ applies the NEQ predicate on the "bedrooms" field.
func BedroomsNEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldBedrooms, v))
}

// BedroomsIn applies the In predicate on the "bedrooms" field.
func BedroomsIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldBedrooms, vs...))
}

// BedroomsNotIn applies the NotIn predicate on the "bedrooms" field.
func BedroomsNotIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldBedrooms, vs...))
}

// BedroomsGT applies the GT predicate on the "bedrooms" field.
func BedroomsGT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldBedrooms, v))
}

// BedroomsGTE applies the GTE predicate on the "bedrooms" field.
func BedroomsGTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldBedrooms, v))
}

// BedroomsLT applies the LT predicate on the "bedrooms" field.
func BedroomsLT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldBedrooms, v))
}

// BedroomsLTE applies the LTE predicate on the "bedrooms" field.
func BedroomsLTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldBedrooms, v))
}

// BedroomsIsNil applies the IsNil predicate on the "bedrooms" field.
func BedroomsIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldBedrooms))
}

// BedroomsNotNil applies the NotNil predicate on the "bedrooms" field.
func BedroomsNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldBedrooms))
}

// BathroomsEQ applies the EQ predicate on the "bathrooms" field.
func BathroomsEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldBathrooms, v))
}

// BathroomsNEQ applies the NEQ predicate on the "bathrooms" field.
func BathroomsNEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldBathrooms, v))
}

// BathroomsIn applies the In predicate on the "bathrooms" field.
func BathroomsIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldBathrooms, vs...))
}

// BathroomsNotIn applies the NotIn predicate on the "bathrooms" field.
func BathroomsNotIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldBathrooms, vs...))
}

// BathroomsGT applies the GT predicate on the "bathrooms" field.
func BathroomsGT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldBathrooms, v))
}

// BathroomsGTE applies the GTE predicate on the "bathrooms" field.
func BathroomsGTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldBathrooms, v))
}

// BathroomsLT applies the LT predicate on the "bathrooms" field.
func BathroomsLT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldBathrooms, v))
}

// BathroomsLTE applies the LTE predicate on the "bathrooms" field.
func BathroomsLTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldBathrooms, v))
}

// BathroomsIsNil applies the IsNil predicate on the "bathrooms" field.
func BathroomsIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldBathrooms))
}

// BathroomsNotNil applies the NotNil predicate on the "bathrooms" field.
func BathroomsNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldBathrooms))
}

// FloorEQ applies the EQ predicate on the "floor" field.
func FloorEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFloor, v))
}

// FloorNEQ applies the NEQ predicate on the "floor" field.
func FloorNEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldFloor, v))
}

// FloorIn applies the In predicate on the "floor" field.
func FloorIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldFloor, vs...))
}

// FloorNotIn applies the NotIn predicate on the "floor" field.
func FloorNotIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldFloor, vs...))
}

// FloorGT applies the GT predicate on the "floor" field.
func FloorGT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldFloor, v))
}

// FloorGTE applies the GTE predicate on the "floor" field.
func FloorGTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldFloor, v))
}

// FloorLT applies the LT predicate on the "floor" field.
func FloorLT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldFloor, v))
}

// FloorLTE applies the LTE predicate on the "floor" field.
func FloorLTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldFloor, v))
}

// FloorIsNil applies the IsNil predicate on the "floor" field.
func FloorIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldFloor))
}

// FloorNotNil applies the NotNil predicate on the "floor" field.
func FloorNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldFloor))
}

// AmenitiesIsNil applies the IsNil predicate on the "amenities" field.
func AmenitiesIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldAmenities))
}

// AmenitiesNotNil applies the NotNil predicate on the "amenities" field.
func AmenitiesNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldAmenities))
}

// FloorPlanEQ applies the EQ predicate on the "floor_plan" field.
func FloorPlanEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFloorPlan, v))
}

// FloorPlanNEQ applies the NEQ predicate on the "floor_plan" field.
func FloorPlanNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldFloorPlan, v))
}

// FloorPlanIn applies the In predicate on the "floor_plan" field.
func FloorPlanIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldFloorPlan, vs...))
}

// FloorPlanNotIn applies the NotIn predicate on the "floor_plan" field.
func FloorPlanNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldFloorPlan, vs...))
}

// FloorPlanGT applies the GT predicate on the "floor_plan" field.
func FloorPlanGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldFloorPlan, v))
}

// FloorPlanGTE applies the GTE predicate on the "floor_plan" field.
func FloorPlanGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldFloorPlan, v))
}

// FloorPlanLT applies the LT predicate on the "floor_plan" field.
func FloorPlanLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldFloorPlan, v))
}

// FloorPlanLTE applies the LTE predicate on the "floor_plan" field.
func FloorPlanLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldFloorPlan, v))
}

// FloorPlanContains applies the Contains predicate on the "floor_plan" field.
func FloorPlanContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldFloorPlan, v))
}

// FloorPlanHasPrefix applies the HasPrefix predicate on the "floor_plan" field.
func FloorPlanHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldFloorPlan, v))
}

// FloorPlanHasSuffix applies the HasSuffix predicate on the "floor_plan" field.
func FloorPlanHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldFloorPlan, v))
}

// FloorPlanIsNil applies the IsNil predicate on the "floor_plan" field.
func FloorPlanIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldFloorPlan))
}

// FloorPlanNotNil applies the NotNil predicate on the "floor_plan" field.
func FloorPlanNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldFloorPlan))
}

// FloorPlanEqualFold applies the EqualFold predicate on the "floor_plan" field.
func FloorPlanEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldFloorPlan, v))
}

// FloorPlanContainsFold applies the ContainsFold predicate on the "floor_plan" field.
func FloorPlanContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldFloorPlan, v))
}

// AdaAccessibleEQ applies the EQ predicate on the "ada_accessible" field.
func AdaAccessibleEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAdaAccessible, v))
}

// AdaAccessibleNEQ applies the NEQ predicate on the "ada_accessible" field.
func AdaAccessibleNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldAdaAccessible, v))
}

// PetFriendlyEQ applies the EQ predicate on the "pet_friendly" field.
func PetFriendlyEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldPetFriendly, v))
}

// PetFriendlyNEQ applies the NEQ predicate on the "pet_friendly" field.
func PetFriendlyNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldPetFriendly, v))
}

// FurnishedEQ applies the EQ predicate on the "furnished" field.
func FurnishedEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFurnished, v))
}

// FurnishedNEQ applies the NEQ predicate on the "furnished" field.
func FurnishedNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldFurnished, v))
}

// MarketRentAmountCentsEQ applies the EQ predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsEQ(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsNEQ applies the NEQ predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsNEQ(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsIn applies the In predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsIn(vs ...int64) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldMarketRentAmountCents, vs...))
}

// MarketRentAmountCentsNotIn applies the NotIn predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsNotIn(vs ...int64) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldMarketRentAmountCents, vs...))
}

// MarketRentAmountCentsGT applies the GT predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsGT(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsGTE applies the GTE predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsGTE(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsLT applies the LT predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsLT(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsLTE applies the LTE predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsLTE(v int64) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldMarketRentAmountCents, v))
}

// MarketRentAmountCentsIsNil applies the IsNil predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldMarketRentAmountCents))
}

// MarketRentAmountCentsNotNil applies the NotNil predicate on the "market_rent_amount_cents" field.
func MarketRentAmountCentsNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldMarketRentAmountCents))
}

// MarketRentCurrencyEQ applies the EQ predicate on the "market_rent_currency" field.
func MarketRentCurrencyEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyNEQ applies the NEQ predicate on the "market_rent_currency" field.
func MarketRentCurrencyNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyIn applies the In predicate on the "market_rent_currency" field.
func MarketRentCurrencyIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldMarketRentCurrency, vs...))
}

// MarketRentCurrencyNotIn applies the NotIn predicate on the "market_rent_currency" field.
func MarketRentCurrencyNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldMarketRentCurrency, vs...))
}

// MarketRentCurrencyGT applies the GT predicate on the "market_rent_currency" field.
func MarketRentCurrencyGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyGTE applies the GTE predicate on the "market_rent_currency" field.
func MarketRentCurrencyGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyLT applies the LT predicate on the "market_rent_currency" field.
func MarketRentCurrencyLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyLTE applies the LTE predicate on the "market_rent_currency" field.
func MarketRentCurrencyLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyContains applies the Contains predicate on the "market_rent_currency" field.
func MarketRentCurrencyContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyHasPrefix applies the HasPrefix predicate on the "market_rent_currency" field.
func MarketRentCurrencyHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyHasSuffix applies the HasSuffix predicate on the "market_rent_currency" field.
func MarketRentCurrencyHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyIsNil applies the IsNil predicate on the "market_rent_currency" field.
func MarketRentCurrencyIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldMarketRentCurrency))
}

// MarketRentCurrencyNotNil applies the NotNil predicate on the "market_rent_currency" field.
func MarketRentCurrencyNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldMarketRentCurrency))
}

// MarketRentCurrencyEqualFold applies the EqualFold predicate on the "market_rent_currency" field.
func MarketRentCurrencyEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldMarketRentCurrency, v))
}

// MarketRentCurrencyContainsFold applies the ContainsFold predicate on the "market_rent_currency" field.
func MarketRentCurrencyContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldMarketRentCurrency, v))
}

// AmiRestrictionEQ applies the EQ predicate on the "ami_restriction" field.
func AmiRestrictionEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldAmiRestriction, v))
}

// AmiRestrictionNEQ applies the NEQ predicate on the "ami_restriction" field.
func AmiRestrictionNEQ(v int) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldAmiRestriction, v))
}

// AmiRestrictionIn applies the In predicate on the "ami_restriction" field.
func AmiRestrictionIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldAmiRestriction, vs...))
}

// AmiRestrictionNotIn applies the NotIn predicate on the "ami_restriction" field.
func AmiRestrictionNotIn(vs ...int) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldAmiRestriction, vs...))
}

// AmiRestrictionGT applies the GT predicate on the "ami_restriction" field.
func AmiRestrictionGT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldAmiRestriction, v))
}

// AmiRestrictionGTE applies the GTE predicate on the "ami_restriction" field.
func AmiRestrictionGTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldAmiRestriction, v))
}

// AmiRestrictionLT applies the LT predicate on the "ami_restriction" field.
func AmiRestrictionLT(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldAmiRestriction, v))
}

// AmiRestrictionLTE applies the LTE predicate on the "ami_restriction" field.
func AmiRestrictionLTE(v int) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldAmiRestriction, v))
}

// AmiRestrictionIsNil applies the IsNil predicate on the "ami_restriction" field.
func AmiRestrictionIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldAmiRestriction))
}

// AmiRestrictionNotNil applies the NotNil predicate on the "ami_restriction" field.
func AmiRestrictionNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldAmiRestriction))
}

// HasProperty applies the HasEdge predicate on the "property" edge.
func HasProperty() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PropertyTable, PropertyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyWith applies the HasEdge predicate on the "property" edge with a given conditions (other predicates).
func HasPropertyWith(preds ...predicate.Property) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := newPropertyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLeases applies the HasEdge predicate on the "leases" edge.
func HasLeases() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LeasesTable, LeasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeasesWith applies the HasEdge predicate on the "leases" edge with a given conditions (other predicates).
func HasLeasesWith(preds ...predicate.Lease) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := newLeasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActiveLease applies the HasEdge predicate on the "active_lease" edge.
func HasActiveLease() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ActiveLeaseTable, ActiveLeaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActiveLeaseWith applies the HasEdge predicate on the "active_lease" edge with a given conditions (other predicates).
func HasActiveLeaseWith(preds ...predicate.Lease) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := newActiveLeaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplications applies the HasEdge predicate on the "applications" edge.
func HasApplications() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ApplicationsTable, ApplicationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationsWith applies the HasEdge predicate on the "applications" edge with a given conditions (other predicates).
func HasApplicationsWith(preds ...predicate.Application) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := newApplicationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.NotPredicates(p))
}
