// Code generated by ent, DO NOT EDIT.

package portfolio

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedBy, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCorrelationID, v))
}

// AgentGoalID applies equality check predicate on the "agent_goal_id" field. It's identical to AgentGoalIDEQ.
func AgentGoalID(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldAgentGoalID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldName, v))
}

// RequiresTrustAccounting applies equality check predicate on the "requires_trust_accounting" field. It's identical to RequiresTrustAccountingEQ.
func RequiresTrustAccounting(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldRequiresTrustAccounting, v))
}

// TrustBankAccountID applies equality check predicate on the "trust_bank_account_id" field. It's identical to TrustBankAccountIDEQ.
func TrustBankAccountID(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldTrustBankAccountID, v))
}

// DefaultLateFeePolicy applies equality check predicate on the "default_late_fee_policy" field. It's identical to DefaultLateFeePolicyEQ.
func DefaultLateFeePolicy(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDefaultLateFeePolicy, v))
}

// FiscalYearStartMonth applies equality check predicate on the "fiscal_year_start_month" field. It's identical to FiscalYearStartMonthEQ.
func FiscalYearStartMonth(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldFiscalYearStartMonth, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldSource, vs...))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldCorrelationID, v))
}

// AgentGoalIDEQ applies the EQ predicate on the "agent_goal_id" field.
func AgentGoalIDEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldAgentGoalID, v))
}

// AgentGoalIDNEQ applies the NEQ predicate on the "agent_goal_id" field.
func AgentGoalIDNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldAgentGoalID, v))
}

// AgentGoalIDIn applies the In predicate on the "agent_goal_id" field.
func AgentGoalIDIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDNotIn applies the NotIn predicate on the "agent_goal_id" field.
func AgentGoalIDNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDGT applies the GT predicate on the "agent_goal_id" field.
func AgentGoalIDGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldAgentGoalID, v))
}

// AgentGoalIDGTE applies the GTE predicate on the "agent_goal_id" field.
func AgentGoalIDGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldAgentGoalID, v))
}

// AgentGoalIDLT applies the LT predicate on the "agent_goal_id" field.
func AgentGoalIDLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldAgentGoalID, v))
}

// AgentGoalIDLTE applies the LTE predicate on the "agent_goal_id" field.
func AgentGoalIDLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldAgentGoalID, v))
}

// AgentGoalIDContains applies the Contains predicate on the "agent_goal_id" field.
func AgentGoalIDContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldAgentGoalID, v))
}

// AgentGoalIDHasPrefix applies the HasPrefix predicate on the "agent_goal_id" field.
func AgentGoalIDHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldAgentGoalID, v))
}

// AgentGoalIDHasSuffix applies the HasSuffix predicate on the "agent_goal_id" field.
func AgentGoalIDHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldAgentGoalID, v))
}

// AgentGoalIDIsNil applies the IsNil predicate on the "agent_goal_id" field.
func AgentGoalIDIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldAgentGoalID))
}

// AgentGoalIDNotNil applies the NotNil predicate on the "agent_goal_id" field.
func AgentGoalIDNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldAgentGoalID))
}

// AgentGoalIDEqualFold applies the EqualFold predicate on the "agent_goal_id" field.
func AgentGoalIDEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldAgentGoalID, v))
}

// AgentGoalIDContainsFold applies the ContainsFold predicate on the "agent_goal_id" field.
func AgentGoalIDContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldAgentGoalID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldName, v))
}

// ManagementTypeEQ applies the EQ predicate on the "management_type" field.
func ManagementTypeEQ(v ManagementType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldManagementType, v))
}

// ManagementTypeNEQ applies the NEQ predicate on the "management_type" field.
func ManagementTypeNEQ(v ManagementType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldManagementType, v))
}

// ManagementTypeIn applies the In predicate on the "management_type" field.
func ManagementTypeIn(vs ...ManagementType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldManagementType, vs...))
}

// ManagementTypeNotIn applies the NotIn predicate on the "management_type" field.
func ManagementTypeNotIn(vs ...ManagementType) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldManagementType, vs...))
}

// RequiresTrustAccountingEQ applies the EQ predicate on the "requires_trust_accounting" field.
func RequiresTrustAccountingEQ(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldRequiresTrustAccounting, v))
}

// RequiresTrustAccountingNEQ applies the NEQ predicate on the "requires_trust_accounting" field.
func RequiresTrustAccountingNEQ(v bool) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldRequiresTrustAccounting, v))
}

// TrustBankAccountIDEQ applies the EQ predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDNEQ applies the NEQ predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDIn applies the In predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldTrustBankAccountID, vs...))
}

// TrustBankAccountIDNotIn applies the NotIn predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldTrustBankAccountID, vs...))
}

// TrustBankAccountIDGT applies the GT predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDGTE applies the GTE predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDLT applies the LT predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDLTE applies the LTE predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDContains applies the Contains predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDHasPrefix applies the HasPrefix predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDHasSuffix applies the HasSuffix predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDIsNil applies the IsNil predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldTrustBankAccountID))
}

// TrustBankAccountIDNotNil applies the NotNil predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldTrustBankAccountID))
}

// TrustBankAccountIDEqualFold applies the EqualFold predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldTrustBankAccountID, v))
}

// TrustBankAccountIDContainsFold applies the ContainsFold predicate on the "trust_bank_account_id" field.
func TrustBankAccountIDContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldTrustBankAccountID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldStatus, vs...))
}

// DefaultLateFeePolicyEQ applies the EQ predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyNEQ applies the NEQ predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyNEQ(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyIn applies the In predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldDefaultLateFeePolicy, vs...))
}

// DefaultLateFeePolicyNotIn applies the NotIn predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyNotIn(vs ...string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldDefaultLateFeePolicy, vs...))
}

// DefaultLateFeePolicyGT applies the GT predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyGT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyGTE applies the GTE predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyGTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyLT applies the LT predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyLT(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyLTE applies the LTE predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyLTE(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyContains applies the Contains predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyContains(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContains(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyHasPrefix applies the HasPrefix predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyHasPrefix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasPrefix(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyHasSuffix applies the HasSuffix predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyHasSuffix(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldHasSuffix(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyIsNil applies the IsNil predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDefaultLateFeePolicy))
}

// DefaultLateFeePolicyNotNil applies the NotNil predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDefaultLateFeePolicy))
}

// DefaultLateFeePolicyEqualFold applies the EqualFold predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyEqualFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEqualFold(FieldDefaultLateFeePolicy, v))
}

// DefaultLateFeePolicyContainsFold applies the ContainsFold predicate on the "default_late_fee_policy" field.
func DefaultLateFeePolicyContainsFold(v string) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldContainsFold(FieldDefaultLateFeePolicy, v))
}

// DefaultPaymentMethodsIsNil applies the IsNil predicate on the "default_payment_methods" field.
func DefaultPaymentMethodsIsNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIsNull(FieldDefaultPaymentMethods))
}

// DefaultPaymentMethodsNotNil applies the NotNil predicate on the "default_payment_methods" field.
func DefaultPaymentMethodsNotNil() predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotNull(FieldDefaultPaymentMethods))
}

// FiscalYearStartMonthEQ applies the EQ predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthEQ(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldEQ(FieldFiscalYearStartMonth, v))
}

// FiscalYearStartMonthNEQ applies the NEQ predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthNEQ(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNEQ(FieldFiscalYearStartMonth, v))
}

// FiscalYearStartMonthIn applies the In predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthIn(vs ...int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldIn(FieldFiscalYearStartMonth, vs...))
}

// FiscalYearStartMonthNotIn applies the NotIn predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthNotIn(vs ...int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldNotIn(FieldFiscalYearStartMonth, vs...))
}

// FiscalYearStartMonthGT applies the GT predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthGT(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGT(FieldFiscalYearStartMonth, v))
}

// FiscalYearStartMonthGTE applies the GTE predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthGTE(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldGTE(FieldFiscalYearStartMonth, v))
}

// FiscalYearStartMonthLT applies the LT predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthLT(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLT(FieldFiscalYearStartMonth, v))
}

// FiscalYearStartMonthLTE applies the LTE predicate on the "fiscal_year_start_month" field.
func FiscalYearStartMonthLTE(v int) predicate.Portfolio {
	return predicate.Portfolio(sql.FieldLTE(FieldFiscalYearStartMonth, v))
}

// HasProperties applies the HasEdge predicate on the "properties" edge.
func HasProperties() predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PropertiesTable, PropertiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertiesWith applies the HasEdge predicate on the "properties" edge with a given conditions (other predicates).
func HasPropertiesWith(preds ...predicate.Property) predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := newPropertiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Organization) predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTrustAccount applies the HasEdge predicate on the "trust_account" edge.
func HasTrustAccount() predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TrustAccountTable, TrustAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTrustAccountWith applies the HasEdge predicate on the "trust_account" edge with a given conditions (other predicates).
func HasTrustAccountWith(preds ...predicate.BankAccount) predicate.Portfolio {
	return predicate.Portfolio(func(s *sql.Selector) {
		step := newTrustAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Portfolio) predicate.Portfolio {
	return predicate.Portfolio(sql.NotPredicates(p))
}
