// Code generated by ent, DO NOT EDIT.

package leasespace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldUpdatedBy, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCorrelationID, v))
}

// AgentGoalID applies equality check predicate on the "agent_goal_id" field. It's identical to AgentGoalIDEQ.
func AgentGoalID(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldAgentGoalID, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldIsPrimary, v))
}

// SquareFootageLeased applies equality check predicate on the "square_footage_leased" field. It's identical to SquareFootageLeasedEQ.
func SquareFootageLeased(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldSquareFootageLeased, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldSource, vs...))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContainsFold(FieldCorrelationID, v))
}

// AgentGoalIDEQ applies the EQ predicate on the "agent_goal_id" field.
func AgentGoalIDEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldAgentGoalID, v))
}

// AgentGoalIDNEQ applies the NEQ predicate on the "agent_goal_id" field.
func AgentGoalIDNEQ(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldAgentGoalID, v))
}

// AgentGoalIDIn applies the In predicate on the "agent_goal_id" field.
func AgentGoalIDIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDNotIn applies the NotIn predicate on the "agent_goal_id" field.
func AgentGoalIDNotIn(vs ...string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDGT applies the GT predicate on the "agent_goal_id" field.
func AgentGoalIDGT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldAgentGoalID, v))
}

// AgentGoalIDGTE applies the GTE predicate on the "agent_goal_id" field.
func AgentGoalIDGTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldAgentGoalID, v))
}

// AgentGoalIDLT applies the LT predicate on the "agent_goal_id" field.
func AgentGoalIDLT(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldAgentGoalID, v))
}

// AgentGoalIDLTE applies the LTE predicate on the "agent_goal_id" field.
func AgentGoalIDLTE(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldAgentGoalID, v))
}

// AgentGoalIDContains applies the Contains predicate on the "agent_goal_id" field.
func AgentGoalIDContains(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContains(FieldAgentGoalID, v))
}

// AgentGoalIDHasPrefix applies the HasPrefix predicate on the "agent_goal_id" field.
func AgentGoalIDHasPrefix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasPrefix(FieldAgentGoalID, v))
}

// AgentGoalIDHasSuffix applies the HasSuffix predicate on the "agent_goal_id" field.
func AgentGoalIDHasSuffix(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldHasSuffix(FieldAgentGoalID, v))
}

// AgentGoalIDIsNil applies the IsNil predicate on the "agent_goal_id" field.
func AgentGoalIDIsNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIsNull(FieldAgentGoalID))
}

// AgentGoalIDNotNil applies the NotNil predicate on the "agent_goal_id" field.
func AgentGoalIDNotNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotNull(FieldAgentGoalID))
}

// AgentGoalIDEqualFold applies the EqualFold predicate on the "agent_goal_id" field.
func AgentGoalIDEqualFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEqualFold(FieldAgentGoalID, v))
}

// AgentGoalIDContainsFold applies the ContainsFold predicate on the "agent_goal_id" field.
func AgentGoalIDContainsFold(v string) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldContainsFold(FieldAgentGoalID, v))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldIsPrimary, v))
}

// RelationshipEQ applies the EQ predicate on the "relationship" field.
func RelationshipEQ(v Relationship) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldRelationship, v))
}

// RelationshipNEQ applies the NEQ predicate on the "relationship" field.
func RelationshipNEQ(v Relationship) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldRelationship, v))
}

// RelationshipIn applies the In predicate on the "relationship" field.
func RelationshipIn(vs ...Relationship) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldRelationship, vs...))
}

// RelationshipNotIn applies the NotIn predicate on the "relationship" field.
func RelationshipNotIn(vs ...Relationship) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldRelationship, vs...))
}

// SquareFootageLeasedEQ applies the EQ predicate on the "square_footage_leased" field.
func SquareFootageLeasedEQ(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldEQ(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedNEQ applies the NEQ predicate on the "square_footage_leased" field.
func SquareFootageLeasedNEQ(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNEQ(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedIn applies the In predicate on the "square_footage_leased" field.
func SquareFootageLeasedIn(vs ...float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIn(FieldSquareFootageLeased, vs...))
}

// SquareFootageLeasedNotIn applies the NotIn predicate on the "square_footage_leased" field.
func SquareFootageLeasedNotIn(vs ...float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotIn(FieldSquareFootageLeased, vs...))
}

// SquareFootageLeasedGT applies the GT predicate on the "square_footage_leased" field.
func SquareFootageLeasedGT(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGT(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedGTE applies the GTE predicate on the "square_footage_leased" field.
func SquareFootageLeasedGTE(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldGTE(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedLT applies the LT predicate on the "square_footage_leased" field.
func SquareFootageLeasedLT(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLT(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedLTE applies the LTE predicate on the "square_footage_leased" field.
func SquareFootageLeasedLTE(v float64) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldLTE(FieldSquareFootageLeased, v))
}

// SquareFootageLeasedIsNil applies the IsNil predicate on the "square_footage_leased" field.
func SquareFootageLeasedIsNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldIsNull(FieldSquareFootageLeased))
}

// SquareFootageLeasedNotNil applies the NotNil predicate on the "square_footage_leased" field.
func SquareFootageLeasedNotNil() predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.FieldNotNull(FieldSquareFootageLeased))
}

// HasLease applies the HasEdge predicate on the "lease" edge.
func HasLease() predicate.LeaseSpace {
	return predicate.LeaseSpace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LeaseTable, LeaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeaseWith applies the HasEdge predicate on the "lease" edge with a given conditions (other predicates).
func HasLeaseWith(preds ...predicate.Lease) predicate.LeaseSpace {
	return predicate.LeaseSpace(func(s *sql.Selector) {
		step := newLeaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSpace applies the HasEdge predicate on the "space" edge.
func HasSpace() predicate.LeaseSpace {
	return predicate.LeaseSpace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SpaceTable, SpaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpaceWith applies the HasEdge predicate on the "space" edge with a given conditions (other predicates).
func HasSpaceWith(preds ...predicate.Space) predicate.LeaseSpace {
	return predicate.LeaseSpace(func(s *sql.Selector) {
		step := newSpaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeaseSpace) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeaseSpace) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeaseSpace) predicate.LeaseSpace {
	return predicate.LeaseSpace(sql.NotPredicates(p))
}
