// Code generated by ent, DO NOT EDIT.

package propertyjurisdiction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldUpdatedBy, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCorrelationID, v))
}

// AgentGoalID applies equality check predicate on the "agent_goal_id" field. It's identical to AgentGoalIDEQ.
func AgentGoalID(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldAgentGoalID, v))
}

// EffectiveDate applies equality check predicate on the "effective_date" field. It's identical to EffectiveDateEQ.
func EffectiveDate(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldEffectiveDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldEndDate, v))
}

// Verified applies equality check predicate on the "verified" field. It's identical to VerifiedEQ.
func Verified(v bool) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerified, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedBy applies equality check predicate on the "verified_by" field. It's identical to VerifiedByEQ.
func VerifiedBy(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerifiedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldSource, vs...))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContainsFold(FieldCorrelationID, v))
}

// AgentGoalIDEQ applies the EQ predicate on the "agent_goal_id" field.
func AgentGoalIDEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldAgentGoalID, v))
}

// AgentGoalIDNEQ applies the NEQ predicate on the "agent_goal_id" field.
func AgentGoalIDNEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldAgentGoalID, v))
}

// AgentGoalIDIn applies the In predicate on the "agent_goal_id" field.
func AgentGoalIDIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDNotIn applies the NotIn predicate on the "agent_goal_id" field.
func AgentGoalIDNotIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDGT applies the GT predicate on the "agent_goal_id" field.
func AgentGoalIDGT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldAgentGoalID, v))
}

// AgentGoalIDGTE applies the GTE predicate on the "agent_goal_id" field.
func AgentGoalIDGTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldAgentGoalID, v))
}

// AgentGoalIDLT applies the LT predicate on the "agent_goal_id" field.
func AgentGoalIDLT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldAgentGoalID, v))
}

// AgentGoalIDLTE applies the LTE predicate on the "agent_goal_id" field.
func AgentGoalIDLTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldAgentGoalID, v))
}

// AgentGoalIDContains applies the Contains predicate on the "agent_goal_id" field.
func AgentGoalIDContains(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContains(FieldAgentGoalID, v))
}

// AgentGoalIDHasPrefix applies the HasPrefix predicate on the "agent_goal_id" field.
func AgentGoalIDHasPrefix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasPrefix(FieldAgentGoalID, v))
}

// AgentGoalIDHasSuffix applies the HasSuffix predicate on the "agent_goal_id" field.
func AgentGoalIDHasSuffix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasSuffix(FieldAgentGoalID, v))
}

// AgentGoalIDIsNil applies the IsNil predicate on the "agent_goal_id" field.
func AgentGoalIDIsNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIsNull(FieldAgentGoalID))
}

// AgentGoalIDNotNil applies the NotNil predicate on the "agent_goal_id" field.
func AgentGoalIDNotNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotNull(FieldAgentGoalID))
}

// AgentGoalIDEqualFold applies the EqualFold predicate on the "agent_goal_id" field.
func AgentGoalIDEqualFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEqualFold(FieldAgentGoalID, v))
}

// AgentGoalIDContainsFold applies the ContainsFold predicate on the "agent_goal_id" field.
func AgentGoalIDContainsFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContainsFold(FieldAgentGoalID, v))
}

// EffectiveDateEQ applies the EQ predicate on the "effective_date" field.
func EffectiveDateEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldEffectiveDate, v))
}

// EffectiveDateNEQ applies the NEQ predicate on the "effective_date" field.
func EffectiveDateNEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldEffectiveDate, v))
}

// EffectiveDateIn applies the In predicate on the "effective_date" field.
func EffectiveDateIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldEffectiveDate, vs...))
}

// EffectiveDateNotIn applies the NotIn predicate on the "effective_date" field.
func EffectiveDateNotIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldEffectiveDate, vs...))
}

// EffectiveDateGT applies the GT predicate on the "effective_date" field.
func EffectiveDateGT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldEffectiveDate, v))
}

// EffectiveDateGTE applies the GTE predicate on the "effective_date" field.
func EffectiveDateGTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldEffectiveDate, v))
}

// EffectiveDateLT applies the LT predicate on the "effective_date" field.
func EffectiveDateLT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldEffectiveDate, v))
}

// EffectiveDateLTE applies the LTE predicate on the "effective_date" field.
func EffectiveDateLTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldEffectiveDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotNull(FieldEndDate))
}

// LookupSourceEQ applies the EQ predicate on the "lookup_source" field.
func LookupSourceEQ(v LookupSource) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldLookupSource, v))
}

// LookupSourceNEQ applies the NEQ predicate on the "lookup_source" field.
func LookupSourceNEQ(v LookupSource) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldLookupSource, v))
}

// LookupSourceIn applies the In predicate on the "lookup_source" field.
func LookupSourceIn(vs ...LookupSource) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldLookupSource, vs...))
}

// LookupSourceNotIn applies the NotIn predicate on the "lookup_source" field.
func LookupSourceNotIn(vs ...LookupSource) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldLookupSource, vs...))
}

// VerifiedEQ applies the EQ predicate on the "verified" field.
func VerifiedEQ(v bool) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerified, v))
}

// VerifiedNEQ applies the NEQ predicate on the "verified" field.
func VerifiedNEQ(v bool) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldVerified, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotNull(FieldVerifiedAt))
}

// VerifiedByEQ applies the EQ predicate on the "verified_by" field.
func VerifiedByEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEQ(FieldVerifiedBy, v))
}

// VerifiedByNEQ applies the NEQ predicate on the "verified_by" field.
func VerifiedByNEQ(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNEQ(FieldVerifiedBy, v))
}

// VerifiedByIn applies the In predicate on the "verified_by" field.
func VerifiedByIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIn(FieldVerifiedBy, vs...))
}

// VerifiedByNotIn applies the NotIn predicate on the "verified_by" field.
func VerifiedByNotIn(vs ...string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotIn(FieldVerifiedBy, vs...))
}

// VerifiedByGT applies the GT predicate on the "verified_by" field.
func VerifiedByGT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGT(FieldVerifiedBy, v))
}

// VerifiedByGTE applies the GTE predicate on the "verified_by" field.
func VerifiedByGTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldGTE(FieldVerifiedBy, v))
}

// VerifiedByLT applies the LT predicate on the "verified_by" field.
func VerifiedByLT(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLT(FieldVerifiedBy, v))
}

// VerifiedByLTE applies the LTE predicate on the "verified_by" field.
func VerifiedByLTE(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldLTE(FieldVerifiedBy, v))
}

// VerifiedByContains applies the Contains predicate on the "verified_by" field.
func VerifiedByContains(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContains(FieldVerifiedBy, v))
}

// VerifiedByHasPrefix applies the HasPrefix predicate on the "verified_by" field.
func VerifiedByHasPrefix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasPrefix(FieldVerifiedBy, v))
}

// VerifiedByHasSuffix applies the HasSuffix predicate on the "verified_by" field.
func VerifiedByHasSuffix(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldHasSuffix(FieldVerifiedBy, v))
}

// VerifiedByIsNil applies the IsNil predicate on the "verified_by" field.
func VerifiedByIsNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldIsNull(FieldVerifiedBy))
}

// VerifiedByNotNil applies the NotNil predicate on the "verified_by" field.
func VerifiedByNotNil() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldNotNull(FieldVerifiedBy))
}

// VerifiedByEqualFold applies the EqualFold predicate on the "verified_by" field.
func VerifiedByEqualFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldEqualFold(FieldVerifiedBy, v))
}

// VerifiedByContainsFold applies the ContainsFold predicate on the "verified_by" field.
func VerifiedByContainsFold(v string) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.FieldContainsFold(FieldVerifiedBy, v))
}

// HasProperty applies the HasEdge predicate on the "property" edge.
func HasProperty() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PropertyTable, PropertyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyWith applies the HasEdge predicate on the "property" edge with a given conditions (other predicates).
func HasPropertyWith(preds ...predicate.Property) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(func(s *sql.Selector) {
		step := newPropertyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJurisdiction applies the HasEdge predicate on the "jurisdiction" edge.
func HasJurisdiction() predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, JurisdictionTable, JurisdictionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJurisdictionWith applies the HasEdge predicate on the "jurisdiction" edge with a given conditions (other predicates).
func HasJurisdictionWith(preds ...predicate.Jurisdiction) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(func(s *sql.Selector) {
		step := newJurisdictionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PropertyJurisdiction) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PropertyJurisdiction) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PropertyJurisdiction) predicate.PropertyJurisdiction {
	return predicate.PropertyJurisdiction(sql.NotPredicates(p))
}
