-- Create "accounts" table
CREATE TABLE `accounts` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `account_number` text NOT NULL,
  `name` text NOT NULL,
  `description` text NULL,
  `account_type` text NOT NULL,
  `account_subtype` text NOT NULL,
  `parent_account_id` uuid NULL,
  `depth` integer NOT NULL,
  `dimensions` json NULL,
  `normal_balance` text NOT NULL,
  `is_header` bool NOT NULL DEFAULT false,
  `is_system` bool NOT NULL DEFAULT false,
  `allows_direct_posting` bool NOT NULL DEFAULT true,
  `status` text NOT NULL,
  `is_trust_account` bool NOT NULL DEFAULT false,
  `trust_type` text NULL,
  `budget_amount_amount_cents` integer NULL,
  `budget_amount_currency` text NULL DEFAULT 'USD',
  `tax_line` text NULL,
  `account_children` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `accounts_accounts_children` FOREIGN KEY (`account_children`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "applications" table
CREATE TABLE `applications` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `status` text NOT NULL,
  `desired_move_in` datetime NOT NULL,
  `desired_lease_term_months` integer NOT NULL,
  `screening_request_id` text NULL,
  `screening_completed` datetime NULL,
  `credit_score` integer NULL,
  `background_clear` bool NOT NULL DEFAULT false,
  `income_verified` bool NOT NULL DEFAULT false,
  `income_to_rent_ratio` real NULL,
  `decision_by` text NULL,
  `decision_at` datetime NULL,
  `decision_reason` text NULL,
  `conditions` json NULL,
  `application_fee_amount_cents` integer NOT NULL,
  `application_fee_currency` text NOT NULL DEFAULT 'USD',
  `fee_paid` bool NOT NULL DEFAULT false,
  `applicant_person_id` uuid NOT NULL,
  `lease_application` uuid NULL,
  `person_applications` uuid NULL,
  `property_applications` uuid NULL,
  `space_applications` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `applications_spaces_applications` FOREIGN KEY (`space_applications`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `applications_properties_applications` FOREIGN KEY (`property_applications`) REFERENCES `properties` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `applications_persons_applications` FOREIGN KEY (`person_applications`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `applications_leases_application` FOREIGN KEY (`lease_application`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `applications_persons_applicant` FOREIGN KEY (`applicant_person_id`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "applications_lease_application_key" to table: "applications"
CREATE UNIQUE INDEX `applications_lease_application_key` ON `applications` (`lease_application`);
-- Create "bank_accounts" table
CREATE TABLE `bank_accounts` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `name` text NOT NULL,
  `account_type` text NOT NULL,
  `bank_name` text NOT NULL,
  `routing_number` text NULL,
  `account_number_last_four` text NOT NULL,
  `property_id` text NULL,
  `entity_id` text NULL,
  `status` text NOT NULL,
  `current_balance_amount_cents` integer NULL,
  `current_balance_currency` text NULL DEFAULT 'USD',
  `last_reconciled_at` datetime NULL,
  `is_trust` bool NOT NULL DEFAULT false,
  `trust_state` text NULL,
  `commingling_allowed` bool NOT NULL DEFAULT false,
  `account_bank_accounts` uuid NULL,
  `bank_account_gl_account` uuid NOT NULL,
  `portfolio_trust_account` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `bank_accounts_portfolios_trust_account` FOREIGN KEY (`portfolio_trust_account`) REFERENCES `portfolios` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `bank_accounts_accounts_gl_account` FOREIGN KEY (`bank_account_gl_account`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `bank_accounts_accounts_bank_accounts` FOREIGN KEY (`account_bank_accounts`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "bank_accounts_portfolio_trust_account_key" to table: "bank_accounts"
CREATE UNIQUE INDEX `bank_accounts_portfolio_trust_account_key` ON `bank_accounts` (`portfolio_trust_account`);
-- Create "buildings" table
CREATE TABLE `buildings` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `name` text NOT NULL,
  `building_type` text NOT NULL,
  `address` json NULL,
  `description` text NULL,
  `status` text NOT NULL,
  `floors` integer NULL,
  `year_built` integer NULL,
  `total_square_footage` real NULL,
  `total_rentable_square_footage` real NULL,
  `property_buildings` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `buildings_properties_buildings` FOREIGN KEY (`property_buildings`) REFERENCES `properties` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "journal_entries" table
CREATE TABLE `journal_entries` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `entry_date` datetime NOT NULL,
  `posted_date` datetime NOT NULL,
  `description` text NOT NULL,
  `source_type` text NOT NULL,
  `source_id` text NULL,
  `status` text NOT NULL,
  `approved_by` text NULL,
  `approved_at` datetime NULL,
  `batch_id` text NULL,
  `entity_id` text NULL,
  `property_id` text NULL,
  `reverses_journal_id` text NULL,
  `reversed_by_journal_id` text NULL,
  `lines` json NOT NULL,
  PRIMARY KEY (`id`)
);
-- Create "leases" table
CREATE TABLE `leases` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `property_id` text NOT NULL,
  `tenant_role_ids` json NOT NULL,
  `guarantor_role_ids` json NULL,
  `lease_type` text NOT NULL,
  `status` text NOT NULL,
  `liability_type` text NOT NULL DEFAULT 'joint_and_several',
  `term` json NOT NULL,
  `lease_commencement_date` datetime NULL,
  `rent_commencement_date` datetime NULL,
  `base_rent_amount_cents` integer NOT NULL,
  `base_rent_currency` text NOT NULL DEFAULT 'USD',
  `security_deposit_amount_cents` integer NOT NULL,
  `security_deposit_currency` text NOT NULL DEFAULT 'USD',
  `rent_schedule` json NULL,
  `recurring_charges` json NULL,
  `late_fee_policy` json NULL,
  `cam_terms` json NULL,
  `tenant_improvement` json NULL,
  `renewal_options` json NULL,
  `usage_charges` json NULL,
  `percentage_rent` json NULL,
  `expansion_rights` json NULL,
  `contraction_rights` json NULL,
  `subsidy` json NULL,
  `move_in_date` datetime NULL,
  `move_out_date` datetime NULL,
  `notice_date` datetime NULL,
  `notice_required_days` integer NOT NULL,
  `check_in_time` text NULL,
  `check_out_time` text NULL,
  `cleaning_fee_amount_cents` integer NULL,
  `cleaning_fee_currency` text NULL DEFAULT 'USD',
  `platform_booking_id` text NULL,
  `membership_tier` text NULL,
  `is_sublease` bool NOT NULL DEFAULT false,
  `sublease_billing` text NOT NULL DEFAULT 'through_master_tenant',
  `signing_method` text NULL,
  `signed_at` datetime NULL,
  `document_id` text NULL,
  `lease_subleases` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `leases_leases_subleases` FOREIGN KEY (`lease_subleases`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "lease_spaces" table
CREATE TABLE `lease_spaces` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `is_primary` bool NOT NULL DEFAULT true,
  `relationship` text NOT NULL,
  `effective` json NOT NULL,
  `square_footage_leased` real NULL,
  `lease_lease_spaces` uuid NULL,
  `lease_space_lease` uuid NOT NULL,
  `lease_space_space` uuid NOT NULL,
  `space_lease_spaces` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lease_spaces_spaces_lease_spaces` FOREIGN KEY (`space_lease_spaces`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `lease_spaces_spaces_space` FOREIGN KEY (`lease_space_space`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `lease_spaces_leases_lease` FOREIGN KEY (`lease_space_lease`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `lease_spaces_leases_lease_spaces` FOREIGN KEY (`lease_lease_spaces`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "ledger_entries" table
CREATE TABLE `ledger_entries` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `entry_type` text NOT NULL,
  `amount_amount_cents` integer NOT NULL,
  `amount_currency` text NOT NULL DEFAULT 'USD',
  `effective_date` datetime NOT NULL,
  `posted_date` datetime NOT NULL,
  `description` text NOT NULL,
  `charge_code` text NOT NULL,
  `memo` text NULL,
  `bank_account_id` text NULL,
  `bank_transaction_id` text NULL,
  `reconciled` bool NOT NULL DEFAULT false,
  `reconciliation_id` text NULL,
  `reconciled_at` datetime NULL,
  `adjusts_entry_id` text NULL,
  `account_entries` uuid NULL,
  `journal_entry_ledger_entries` uuid NULL,
  `lease_ledger_entries` uuid NULL,
  `ledger_entry_journal_entry` uuid NOT NULL,
  `ledger_entry_account` uuid NOT NULL,
  `ledger_entry_property` uuid NOT NULL,
  `ledger_entry_space` uuid NULL,
  `ledger_entry_person` uuid NULL,
  `person_ledger_entries` uuid NULL,
  `property_ledger_entries` uuid NULL,
  `space_ledger_entries` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ledger_entries_spaces_ledger_entries` FOREIGN KEY (`space_ledger_entries`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_properties_ledger_entries` FOREIGN KEY (`property_ledger_entries`) REFERENCES `properties` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_persons_ledger_entries` FOREIGN KEY (`person_ledger_entries`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_persons_person` FOREIGN KEY (`ledger_entry_person`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_spaces_space` FOREIGN KEY (`ledger_entry_space`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_properties_property` FOREIGN KEY (`ledger_entry_property`) REFERENCES `properties` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `ledger_entries_accounts_account` FOREIGN KEY (`ledger_entry_account`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `ledger_entries_journal_entries_journal_entry` FOREIGN KEY (`ledger_entry_journal_entry`) REFERENCES `journal_entries` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `ledger_entries_leases_ledger_entries` FOREIGN KEY (`lease_ledger_entries`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_journal_entries_ledger_entries` FOREIGN KEY (`journal_entry_ledger_entries`) REFERENCES `journal_entries` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `ledger_entries_accounts_entries` FOREIGN KEY (`account_entries`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "organizations" table
CREATE TABLE `organizations` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `legal_name` text NOT NULL,
  `dba_name` text NULL,
  `org_type` text NOT NULL,
  `tax_id` text NULL,
  `tax_id_type` text NULL,
  `status` text NOT NULL,
  `address` json NULL,
  `contact_methods` json NULL,
  `state_of_incorporation` text NULL,
  `formation_date` datetime NULL,
  `management_license` text NULL,
  `license_state` text NULL,
  `license_expiry` datetime NULL,
  `organization_subsidiaries` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `organizations_organizations_subsidiaries` FOREIGN KEY (`organization_subsidiaries`) REFERENCES `organizations` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "persons" table
CREATE TABLE `persons` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `first_name` text NOT NULL,
  `last_name` text NOT NULL,
  `display_name` text NOT NULL,
  `date_of_birth` datetime NULL,
  `ssn_last_four` text NULL,
  `contact_methods` json NOT NULL,
  `preferred_contact` text NOT NULL DEFAULT 'email',
  `language_preference` text NOT NULL,
  `timezone` text NULL,
  `do_not_contact` bool NOT NULL DEFAULT false,
  `identity_verified` bool NOT NULL DEFAULT false,
  `verification_method` text NULL,
  `verified_at` datetime NULL,
  `tags` json NULL,
  PRIMARY KEY (`id`)
);
-- Create "person_roles" table
CREATE TABLE `person_roles` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `role_type` text NOT NULL,
  `scope_type` text NOT NULL,
  `scope_id` text NOT NULL,
  `status` text NOT NULL,
  `effective` json NOT NULL,
  `attributes` json NULL,
  `person_roles` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `person_roles_persons_roles` FOREIGN KEY (`person_roles`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "portfolios" table
CREATE TABLE `portfolios` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `name` text NOT NULL,
  `management_type` text NOT NULL,
  `requires_trust_accounting` bool NOT NULL,
  `trust_bank_account_id` text NULL,
  `status` text NOT NULL,
  `default_payment_methods` json NULL,
  `fiscal_year_start_month` integer NOT NULL,
  `organization_owned_portfolios` uuid NULL,
  `portfolio_owner` uuid NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `portfolios_organizations_owner` FOREIGN KEY (`portfolio_owner`) REFERENCES `organizations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `portfolios_organizations_owned_portfolios` FOREIGN KEY (`organization_owned_portfolios`) REFERENCES `organizations` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "properties" table
CREATE TABLE `properties` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `name` text NOT NULL,
  `address` json NOT NULL,
  `property_type` text NOT NULL,
  `status` text NOT NULL,
  `year_built` integer NOT NULL,
  `total_square_footage` real NOT NULL,
  `total_spaces` integer NOT NULL,
  `lot_size_sqft` real NULL,
  `stories` integer NULL,
  `parking_spaces` integer NULL,
  `jurisdiction_id` text NULL,
  `rent_controlled` bool NOT NULL DEFAULT false,
  `compliance_programs` json NULL,
  `requires_lead_disclosure` bool NOT NULL,
  `chart_of_accounts_id` text NULL,
  `insurance_policy_number` text NULL,
  `insurance_expiry` datetime NULL,
  `bank_account_properties` uuid NULL,
  `portfolio_properties` uuid NULL,
  `property_bank_account` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `properties_bank_accounts_bank_account` FOREIGN KEY (`property_bank_account`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `properties_portfolios_properties` FOREIGN KEY (`portfolio_properties`) REFERENCES `portfolios` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `properties_bank_accounts_properties` FOREIGN KEY (`bank_account_properties`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "reconciliations" table
CREATE TABLE `reconciliations` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `period_start` datetime NOT NULL,
  `period_end` datetime NOT NULL,
  `statement_balance_amount_cents` integer NOT NULL,
  `statement_balance_currency` text NOT NULL DEFAULT 'USD',
  `system_balance_amount_cents` integer NOT NULL,
  `system_balance_currency` text NOT NULL DEFAULT 'USD',
  `difference_amount_cents` integer NOT NULL,
  `difference_currency` text NOT NULL DEFAULT 'USD',
  `status` text NOT NULL,
  `matched_transaction_count` integer NOT NULL,
  `unmatched_transaction_count` integer NOT NULL,
  `completed_by` text NULL,
  `completed_at` datetime NULL,
  `approved_by` text NULL,
  `approved_at` datetime NULL,
  `bank_account_reconciliations` uuid NULL,
  `reconciliation_bank_account` uuid NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `reconciliations_bank_accounts_bank_account` FOREIGN KEY (`reconciliation_bank_account`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT `reconciliations_bank_accounts_reconciliations` FOREIGN KEY (`bank_account_reconciliations`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "spaces" table
CREATE TABLE `spaces` (
  `id` uuid NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` text NOT NULL,
  `updated_by` text NOT NULL,
  `source` text NOT NULL,
  `correlation_id` text NULL,
  `agent_goal_id` text NULL,
  `space_number` text NOT NULL,
  `space_type` text NOT NULL,
  `status` text NOT NULL,
  `leasable` bool NOT NULL,
  `shared_with_parent` bool NOT NULL DEFAULT false,
  `square_footage` real NOT NULL,
  `bedrooms` integer NULL,
  `bathrooms` real NULL,
  `floor` integer NULL,
  `amenities` json NULL,
  `floor_plan` text NULL,
  `ada_accessible` bool NOT NULL DEFAULT false,
  `pet_friendly` bool NOT NULL DEFAULT true,
  `furnished` bool NOT NULL DEFAULT false,
  `specialized_infrastructure` json NULL,
  `market_rent_amount_cents` integer NULL,
  `market_rent_currency` text NULL DEFAULT 'USD',
  `ami_restriction` integer NULL,
  `active_lease_id` text NULL,
  `building_spaces` uuid NULL,
  `property_spaces` uuid NULL,
  `space_children` uuid NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `spaces_spaces_children` FOREIGN KEY (`space_children`) REFERENCES `spaces` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `spaces_properties_spaces` FOREIGN KEY (`property_spaces`) REFERENCES `properties` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT `spaces_buildings_spaces` FOREIGN KEY (`building_spaces`) REFERENCES `buildings` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "lease_tenant_roles" table
CREATE TABLE `lease_tenant_roles` (
  `lease_id` uuid NOT NULL,
  `person_role_id` uuid NOT NULL,
  PRIMARY KEY (`lease_id`, `person_role_id`),
  CONSTRAINT `lease_tenant_roles_person_role_id` FOREIGN KEY (`person_role_id`) REFERENCES `person_roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT `lease_tenant_roles_lease_id` FOREIGN KEY (`lease_id`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "lease_guarantor_roles" table
CREATE TABLE `lease_guarantor_roles` (
  `lease_id` uuid NOT NULL,
  `person_role_id` uuid NOT NULL,
  PRIMARY KEY (`lease_id`, `person_role_id`),
  CONSTRAINT `lease_guarantor_roles_person_role_id` FOREIGN KEY (`person_role_id`) REFERENCES `person_roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT `lease_guarantor_roles_lease_id` FOREIGN KEY (`lease_id`) REFERENCES `leases` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "person_organizations" table
CREATE TABLE `person_organizations` (
  `person_id` uuid NOT NULL,
  `organization_id` uuid NOT NULL,
  PRIMARY KEY (`person_id`, `organization_id`),
  CONSTRAINT `person_organizations_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT `person_organizations_person_id` FOREIGN KEY (`person_id`) REFERENCES `persons` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
);
