// Code generated by cmd/entgen from CUE ontology. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/mixin"
	"github.com/google/uuid"
)

// Ensure mixin import is used.
var _ mixin.Schema

// BaseEntity holds the schema definition for the BaseEntity entity.
type BaseEntity struct {
	ent.Schema
}

// Mixin of the BaseEntity.
func (BaseEntity) Mixin() []ent.Mixin {
	return []ent.Mixin{
		AuditMixin{},
	}
}

// Fields of the BaseEntity.
func (BaseEntity) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable().Comment("Primary key"),
	}
}

// Edges of the BaseEntity.
func (BaseEntity) Edges() []ent.Edge {
	return nil
}
