// Code generated by cmd/entgen from CUE ontology. DO NOT EDIT.
package schema

import (
	"context"
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/mixin"
	"github.com/google/uuid"
)

// Ensure mixin import is used.
var _ mixin.Schema

// Portfolio holds the schema definition for the Portfolio entity.
type Portfolio struct {
	ent.Schema
}

// Mixin of the Portfolio.
func (Portfolio) Mixin() []ent.Mixin {
	return []ent.Mixin{
		AuditMixin{},
	}
}

// Fields of the Portfolio.
func (Portfolio) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable().Comment("Primary key"),
		field.String("name").SchemaType(map[string]string{"postgres": "varchar"}),
		field.Enum("management_type").Values("self_managed", "third_party", "hybrid"),
		field.Bool("requires_trust_accounting"),
		field.String("trust_bank_account_id").Optional().Nillable().SchemaType(map[string]string{"postgres": "varchar"}),
		field.Enum("status").Values("active", "inactive", "onboarding", "offboarding"),
		field.JSON("default_payment_methods", []string{}).Optional(),
		field.Int("fiscal_year_start_month"),
	}
}

// Edges of the Portfolio.
func (Portfolio) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("properties", Property.Type).Comment("Portfolio contains Properties"),
		edge.To("owner", Organization.Type).Unique().Required().Comment("Portfolio is owned by Organization"),
		edge.To("trust_account", BankAccount.Type).Unique().Comment("Portfolio uses BankAccount for trust funds"),
	}
}

// ValidPortfolioTransitions defines the allowed state machine transitions.
// Generated from CUE ontology state_machines.cue.
var ValidPortfolioTransitions = map[string][]string{
	"active":      {"inactive", "offboarding"},
	"inactive":    {"active", "offboarding"},
	"offboarding": {"inactive"},
	"onboarding":  {"active"},
}

// Hooks returns cross-field constraint validation hooks.
// Generated from CUE ontology conditional blocks.
func (Portfolio) Hooks() []ent.Hook {
	return []ent.Hook{
		validatePortfolioConstraints(),
	}
}

func validatePortfolioConstraints() ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			getField := func(name string) (interface{}, bool) {
				if v, ok := m.Field(name); ok {
					return v, true
				}
				if v, err := m.OldField(ctx, name); err == nil {
					return v, true
				}
				return nil, false
			}
			toString := func(v interface{}) string {
				if v == nil {
					return ""
				}
				switch s := v.(type) {
				case string:
					return s
				case *string:
					if s != nil {
						return *s
					}
					return ""
				}
				return fmt.Sprint(v)
			}

			// requires_trust_accounting == true → trust_bank_account_id must be non-empty
			if v, ok := getField("requires_trust_accounting"); ok && fmt.Sprint(v) == "true" {
				tid, tidOk := getField("trust_bank_account_id")
				if !tidOk || toString(tid) == "" {
					return nil, fmt.Errorf("portfolio with requires_trust_accounting=true must have trust_bank_account_id set")
				}
			}
			return next.Mutate(ctx, m)
		})
	}
}
