// Code generated by ent, DO NOT EDIT.

package bankaccount

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the bankaccount type in the database.
	Label = "bank_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCorrelationID holds the string denoting the correlation_id field in the database.
	FieldCorrelationID = "correlation_id"
	// FieldAgentGoalID holds the string denoting the agent_goal_id field in the database.
	FieldAgentGoalID = "agent_goal_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldInstitutionName holds the string denoting the institution_name field in the database.
	FieldInstitutionName = "institution_name"
	// FieldRoutingNumber holds the string denoting the routing_number field in the database.
	FieldRoutingNumber = "routing_number"
	// FieldAccountMask holds the string denoting the account_mask field in the database.
	FieldAccountMask = "account_mask"
	// FieldAccountNumberEncrypted holds the string denoting the account_number_encrypted field in the database.
	FieldAccountNumberEncrypted = "account_number_encrypted"
	// FieldPlaidAccountID holds the string denoting the plaid_account_id field in the database.
	FieldPlaidAccountID = "plaid_account_id"
	// FieldPlaidAccessToken holds the string denoting the plaid_access_token field in the database.
	FieldPlaidAccessToken = "plaid_access_token"
	// FieldPropertyID holds the string denoting the property_id field in the database.
	FieldPropertyID = "property_id"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldAcceptsDeposits holds the string denoting the accepts_deposits field in the database.
	FieldAcceptsDeposits = "accepts_deposits"
	// FieldAcceptsPayments holds the string denoting the accepts_payments field in the database.
	FieldAcceptsPayments = "accepts_payments"
	// FieldCurrentBalanceAmountCents holds the string denoting the current_balance_amount_cents field in the database.
	FieldCurrentBalanceAmountCents = "current_balance_amount_cents"
	// FieldCurrentBalanceCurrency holds the string denoting the current_balance_currency field in the database.
	FieldCurrentBalanceCurrency = "current_balance_currency"
	// FieldLastStatementDate holds the string denoting the last_statement_date field in the database.
	FieldLastStatementDate = "last_statement_date"
	// EdgeTrustPortfolio holds the string denoting the trust_portfolio edge name in mutations.
	EdgeTrustPortfolio = "trust_portfolio"
	// EdgeProperties holds the string denoting the properties edge name in mutations.
	EdgeProperties = "properties"
	// EdgeGlAccount holds the string denoting the gl_account edge name in mutations.
	EdgeGlAccount = "gl_account"
	// EdgeReconciliations holds the string denoting the reconciliations edge name in mutations.
	EdgeReconciliations = "reconciliations"
	// Table holds the table name of the bankaccount in the database.
	Table = "bank_accounts"
	// TrustPortfolioTable is the table that holds the trust_portfolio relation/edge.
	TrustPortfolioTable = "bank_accounts"
	// TrustPortfolioInverseTable is the table name for the Portfolio entity.
	// It exists in this package in order to avoid circular dependency with the "portfolio" package.
	TrustPortfolioInverseTable = "portfolios"
	// TrustPortfolioColumn is the table column denoting the trust_portfolio relation/edge.
	TrustPortfolioColumn = "portfolio_trust_account"
	// PropertiesTable is the table that holds the properties relation/edge.
	PropertiesTable = "properties"
	// PropertiesInverseTable is the table name for the Property entity.
	// It exists in this package in order to avoid circular dependency with the "property" package.
	PropertiesInverseTable = "properties"
	// PropertiesColumn is the table column denoting the properties relation/edge.
	PropertiesColumn = "bank_account_properties"
	// GlAccountTable is the table that holds the gl_account relation/edge.
	GlAccountTable = "bank_accounts"
	// GlAccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	GlAccountInverseTable = "accounts"
	// GlAccountColumn is the table column denoting the gl_account relation/edge.
	GlAccountColumn = "bank_account_gl_account"
	// ReconciliationsTable is the table that holds the reconciliations relation/edge.
	ReconciliationsTable = "reconciliations"
	// ReconciliationsInverseTable is the table name for the Reconciliation entity.
	// It exists in this package in order to avoid circular dependency with the "reconciliation" package.
	ReconciliationsInverseTable = "reconciliations"
	// ReconciliationsColumn is the table column denoting the reconciliations relation/edge.
	ReconciliationsColumn = "bank_account_reconciliations"
)

// Columns holds all SQL columns for bankaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldSource,
	FieldCorrelationID,
	FieldAgentGoalID,
	FieldName,
	FieldAccountType,
	FieldInstitutionName,
	FieldRoutingNumber,
	FieldAccountMask,
	FieldAccountNumberEncrypted,
	FieldPlaidAccountID,
	FieldPlaidAccessToken,
	FieldPropertyID,
	FieldEntityID,
	FieldStatus,
	FieldIsDefault,
	FieldAcceptsDeposits,
	FieldAcceptsPayments,
	FieldCurrentBalanceAmountCents,
	FieldCurrentBalanceCurrency,
	FieldLastStatementDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "bank_accounts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_bank_accounts",
	"bank_account_gl_account",
	"portfolio_trust_account",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	UpdatedByValidator func(string) error
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultAcceptsDeposits holds the default value on creation for the "accepts_deposits" field.
	DefaultAcceptsDeposits bool
	// DefaultAcceptsPayments holds the default value on creation for the "accepts_payments" field.
	DefaultAcceptsPayments bool
	// DefaultCurrentBalanceCurrency holds the default value on creation for the "current_balance_currency" field.
	DefaultCurrentBalanceCurrency string
	// CurrentBalanceCurrencyValidator is a validator for the "current_balance_currency" field. It is called by the builders before save.
	CurrentBalanceCurrencyValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Source defines the type for the "source" enum field.
type Source string

// Source values.
const (
	SourceUser      Source = "user"
	SourceAgent     Source = "agent"
	SourceImport    Source = "import"
	SourceSystem    Source = "system"
	SourceMigration Source = "migration"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceUser, SourceAgent, SourceImport, SourceSystem, SourceMigration:
		return nil
	default:
		return fmt.Errorf("bankaccount: invalid enum value for source field: %q", s)
	}
}

// AccountType defines the type for the "account_type" enum field.
type AccountType string

// AccountType values.
const (
	AccountTypeOperating       AccountType = "operating"
	AccountTypeTrust           AccountType = "trust"
	AccountTypeSecurityDeposit AccountType = "security_deposit"
	AccountTypeEscrow          AccountType = "escrow"
	AccountTypeReserve         AccountType = "reserve"
)

func (at AccountType) String() string {
	return string(at)
}

// AccountTypeValidator is a validator for the "account_type" field enum values. It is called by the builders before save.
func AccountTypeValidator(at AccountType) error {
	switch at {
	case AccountTypeOperating, AccountTypeTrust, AccountTypeSecurityDeposit, AccountTypeEscrow, AccountTypeReserve:
		return nil
	default:
		return fmt.Errorf("bankaccount: invalid enum value for account_type field: %q", at)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
	StatusFrozen   Status = "frozen"
	StatusClosed   Status = "closed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusFrozen, StatusClosed:
		return nil
	default:
		return fmt.Errorf("bankaccount: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BankAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCorrelationID orders the results by the correlation_id field.
func ByCorrelationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrelationID, opts...).ToFunc()
}

// ByAgentGoalID orders the results by the agent_goal_id field.
func ByAgentGoalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentGoalID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByInstitutionName orders the results by the institution_name field.
func ByInstitutionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitutionName, opts...).ToFunc()
}

// ByRoutingNumber orders the results by the routing_number field.
func ByRoutingNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingNumber, opts...).ToFunc()
}

// ByAccountMask orders the results by the account_mask field.
func ByAccountMask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountMask, opts...).ToFunc()
}

// ByAccountNumberEncrypted orders the results by the account_number_encrypted field.
func ByAccountNumberEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountNumberEncrypted, opts...).ToFunc()
}

// ByPlaidAccountID orders the results by the plaid_account_id field.
func ByPlaidAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaidAccountID, opts...).ToFunc()
}

// ByPlaidAccessToken orders the results by the plaid_access_token field.
func ByPlaidAccessToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaidAccessToken, opts...).ToFunc()
}

// ByPropertyID orders the results by the property_id field.
func ByPropertyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPropertyID, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByAcceptsDeposits orders the results by the accepts_deposits field.
func ByAcceptsDeposits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptsDeposits, opts...).ToFunc()
}

// ByAcceptsPayments orders the results by the accepts_payments field.
func ByAcceptsPayments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptsPayments, opts...).ToFunc()
}

// ByCurrentBalanceAmountCents orders the results by the current_balance_amount_cents field.
func ByCurrentBalanceAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentBalanceAmountCents, opts...).ToFunc()
}

// ByCurrentBalanceCurrency orders the results by the current_balance_currency field.
func ByCurrentBalanceCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentBalanceCurrency, opts...).ToFunc()
}

// ByLastStatementDate orders the results by the last_statement_date field.
func ByLastStatementDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatementDate, opts...).ToFunc()
}

// ByTrustPortfolioField orders the results by trust_portfolio field.
func ByTrustPortfolioField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrustPortfolioStep(), sql.OrderByField(field, opts...))
	}
}

// ByPropertiesCount orders the results by properties count.
func ByPropertiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPropertiesStep(), opts...)
	}
}

// ByProperties orders the results by properties terms.
func ByProperties(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPropertiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGlAccountField orders the results by gl_account field.
func ByGlAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGlAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByReconciliationsCount orders the results by reconciliations count.
func ByReconciliationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReconciliationsStep(), opts...)
	}
}

// ByReconciliations orders the results by reconciliations terms.
func ByReconciliations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReconciliationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTrustPortfolioStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrustPortfolioInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TrustPortfolioTable, TrustPortfolioColumn),
	)
}
func newPropertiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PropertiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PropertiesTable, PropertiesColumn),
	)
}
func newGlAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GlAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GlAccountTable, GlAccountColumn),
	)
}
func newReconciliationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReconciliationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReconciliationsTable, ReconciliationsColumn),
	)
}
