// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/account"
	"github.com/matthewbaird/ontology/ent/bankaccount"
	"github.com/matthewbaird/ontology/ent/ledgerentry"
	"github.com/matthewbaird/ontology/ent/predicate"
	"github.com/matthewbaird/ontology/internal/types"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountUpdate) SetCreatedBy(v string) *AccountUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCreatedBy(v *string) *AccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccountUpdate) SetUpdatedBy(v string) *AccountUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUpdatedBy(v *string) *AccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AccountUpdate) SetSource(v account.Source) *AccountUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSource(v *account.Source) *AccountUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *AccountUpdate) SetCorrelationID(v string) *AccountUpdate {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCorrelationID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *AccountUpdate) ClearCorrelationID() *AccountUpdate {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *AccountUpdate) SetAgentGoalID(v string) *AccountUpdate {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAgentGoalID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *AccountUpdate) ClearAgentGoalID() *AccountUpdate {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetAccountNumber sets the "account_number" field.
func (_u *AccountUpdate) SetAccountNumber(v string) *AccountUpdate {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccountNumber(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountUpdate) SetDescription(v string) *AccountUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDescription(v *string) *AccountUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountUpdate) ClearDescription() *AccountUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountUpdate) SetAccountType(v account.AccountType) *AccountUpdate {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccountType(v *account.AccountType) *AccountUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetAccountSubtype sets the "account_subtype" field.
func (_u *AccountUpdate) SetAccountSubtype(v account.AccountSubtype) *AccountUpdate {
	_u.mutation.SetAccountSubtype(v)
	return _u
}

// SetNillableAccountSubtype sets the "account_subtype" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccountSubtype(v *account.AccountSubtype) *AccountUpdate {
	if v != nil {
		_u.SetAccountSubtype(*v)
	}
	return _u
}

// SetParentAccountID sets the "parent_account_id" field.
func (_u *AccountUpdate) SetParentAccountID(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetParentAccountID(v)
	return _u
}

// SetNillableParentAccountID sets the "parent_account_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableParentAccountID(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetParentAccountID(*v)
	}
	return _u
}

// ClearParentAccountID clears the value of the "parent_account_id" field.
func (_u *AccountUpdate) ClearParentAccountID() *AccountUpdate {
	_u.mutation.ClearParentAccountID()
	return _u
}

// SetDepth sets the "depth" field.
func (_u *AccountUpdate) SetDepth(v int) *AccountUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDepth(v *int) *AccountUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *AccountUpdate) AddDepth(v int) *AccountUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetDimensions sets the "dimensions" field.
func (_u *AccountUpdate) SetDimensions(v *types.AccountDimensions) *AccountUpdate {
	_u.mutation.SetDimensions(v)
	return _u
}

// ClearDimensions clears the value of the "dimensions" field.
func (_u *AccountUpdate) ClearDimensions() *AccountUpdate {
	_u.mutation.ClearDimensions()
	return _u
}

// SetNormalBalance sets the "normal_balance" field.
func (_u *AccountUpdate) SetNormalBalance(v string) *AccountUpdate {
	_u.mutation.SetNormalBalance(v)
	return _u
}

// SetNillableNormalBalance sets the "normal_balance" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableNormalBalance(v *string) *AccountUpdate {
	if v != nil {
		_u.SetNormalBalance(*v)
	}
	return _u
}

// SetIsHeader sets the "is_header" field.
func (_u *AccountUpdate) SetIsHeader(v bool) *AccountUpdate {
	_u.mutation.SetIsHeader(v)
	return _u
}

// SetNillableIsHeader sets the "is_header" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsHeader(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsHeader(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AccountUpdate) SetIsSystem(v bool) *AccountUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsSystem(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetAllowsDirectPosting sets the "allows_direct_posting" field.
func (_u *AccountUpdate) SetAllowsDirectPosting(v bool) *AccountUpdate {
	_u.mutation.SetAllowsDirectPosting(v)
	return _u
}

// SetNillableAllowsDirectPosting sets the "allows_direct_posting" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAllowsDirectPosting(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetAllowsDirectPosting(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdate) SetStatus(v account.Status) *AccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableStatus(v *account.Status) *AccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsTrustAccount sets the "is_trust_account" field.
func (_u *AccountUpdate) SetIsTrustAccount(v bool) *AccountUpdate {
	_u.mutation.SetIsTrustAccount(v)
	return _u
}

// SetNillableIsTrustAccount sets the "is_trust_account" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsTrustAccount(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsTrustAccount(*v)
	}
	return _u
}

// SetTrustType sets the "trust_type" field.
func (_u *AccountUpdate) SetTrustType(v string) *AccountUpdate {
	_u.mutation.SetTrustType(v)
	return _u
}

// SetNillableTrustType sets the "trust_type" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableTrustType(v *string) *AccountUpdate {
	if v != nil {
		_u.SetTrustType(*v)
	}
	return _u
}

// ClearTrustType clears the value of the "trust_type" field.
func (_u *AccountUpdate) ClearTrustType() *AccountUpdate {
	_u.mutation.ClearTrustType()
	return _u
}

// SetBudgetAmountAmountCents sets the "budget_amount_amount_cents" field.
func (_u *AccountUpdate) SetBudgetAmountAmountCents(v int64) *AccountUpdate {
	_u.mutation.ResetBudgetAmountAmountCents()
	_u.mutation.SetBudgetAmountAmountCents(v)
	return _u
}

// SetNillableBudgetAmountAmountCents sets the "budget_amount_amount_cents" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBudgetAmountAmountCents(v *int64) *AccountUpdate {
	if v != nil {
		_u.SetBudgetAmountAmountCents(*v)
	}
	return _u
}

// AddBudgetAmountAmountCents adds value to the "budget_amount_amount_cents" field.
func (_u *AccountUpdate) AddBudgetAmountAmountCents(v int64) *AccountUpdate {
	_u.mutation.AddBudgetAmountAmountCents(v)
	return _u
}

// ClearBudgetAmountAmountCents clears the value of the "budget_amount_amount_cents" field.
func (_u *AccountUpdate) ClearBudgetAmountAmountCents() *AccountUpdate {
	_u.mutation.ClearBudgetAmountAmountCents()
	return _u
}

// SetBudgetAmountCurrency sets the "budget_amount_currency" field.
func (_u *AccountUpdate) SetBudgetAmountCurrency(v string) *AccountUpdate {
	_u.mutation.SetBudgetAmountCurrency(v)
	return _u
}

// SetNillableBudgetAmountCurrency sets the "budget_amount_currency" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBudgetAmountCurrency(v *string) *AccountUpdate {
	if v != nil {
		_u.SetBudgetAmountCurrency(*v)
	}
	return _u
}

// ClearBudgetAmountCurrency clears the value of the "budget_amount_currency" field.
func (_u *AccountUpdate) ClearBudgetAmountCurrency() *AccountUpdate {
	_u.mutation.ClearBudgetAmountCurrency()
	return _u
}

// SetTaxLine sets the "tax_line" field.
func (_u *AccountUpdate) SetTaxLine(v string) *AccountUpdate {
	_u.mutation.SetTaxLine(v)
	return _u
}

// SetNillableTaxLine sets the "tax_line" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableTaxLine(v *string) *AccountUpdate {
	if v != nil {
		_u.SetTaxLine(*v)
	}
	return _u
}

// ClearTaxLine clears the value of the "tax_line" field.
func (_u *AccountUpdate) ClearTaxLine() *AccountUpdate {
	_u.mutation.ClearTaxLine()
	return _u
}

// AddChildIDs adds the "children" edge to the Account entity by IDs.
func (_u *AccountUpdate) AddChildIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Account entity.
func (_u *AccountUpdate) AddChildren(v ...*Account) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Account entity by ID.
func (_u *AccountUpdate) SetParentID(id uuid.UUID) *AccountUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Account entity by ID if the given value is not nil.
func (_u *AccountUpdate) SetNillableParentID(id *uuid.UUID) *AccountUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Account entity.
func (_u *AccountUpdate) SetParent(v *Account) *AccountUpdate {
	return _u.SetParentID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the LedgerEntry entity by IDs.
func (_u *AccountUpdate) AddEntryIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the LedgerEntry entity.
func (_u *AccountUpdate) AddEntries(v ...*LedgerEntry) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddBankAccountIDs adds the "bank_accounts" edge to the BankAccount entity by IDs.
func (_u *AccountUpdate) AddBankAccountIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.AddBankAccountIDs(ids...)
	return _u
}

// AddBankAccounts adds the "bank_accounts" edges to the BankAccount entity.
func (_u *AccountUpdate) AddBankAccounts(v ...*BankAccount) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBankAccountIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Account entity.
func (_u *AccountUpdate) ClearChildren() *AccountUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Account entities by IDs.
func (_u *AccountUpdate) RemoveChildIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Account entities.
func (_u *AccountUpdate) RemoveChildren(v ...*Account) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Account entity.
func (_u *AccountUpdate) ClearParent() *AccountUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearEntries clears all "entries" edges to the LedgerEntry entity.
func (_u *AccountUpdate) ClearEntries() *AccountUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to LedgerEntry entities by IDs.
func (_u *AccountUpdate) RemoveEntryIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to LedgerEntry entities.
func (_u *AccountUpdate) RemoveEntries(v ...*LedgerEntry) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearBankAccounts clears all "bank_accounts" edges to the BankAccount entity.
func (_u *AccountUpdate) ClearBankAccounts() *AccountUpdate {
	_u.mutation.ClearBankAccounts()
	return _u
}

// RemoveBankAccountIDs removes the "bank_accounts" edge to BankAccount entities by IDs.
func (_u *AccountUpdate) RemoveBankAccountIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.RemoveBankAccountIDs(ids...)
	return _u
}

// RemoveBankAccounts removes "bank_accounts" edges to BankAccount entities.
func (_u *AccountUpdate) RemoveBankAccounts(v ...*BankAccount) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBankAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := account.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Account.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := account.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "Account.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := account.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Account.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := account.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "Account.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountSubtype(); ok {
		if err := account.AccountSubtypeValidator(v); err != nil {
			return &ValidationError{Name: "account_subtype", err: fmt.Errorf(`ent: validator failed for field "Account.account_subtype": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BudgetAmountCurrency(); ok {
		if err := account.BudgetAmountCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "budget_amount_currency", err: fmt.Errorf(`ent: validator failed for field "Account.budget_amount_currency": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(account.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(account.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(account.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(account.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(account.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(account.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(account.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(account.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(account.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(account.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(account.FieldAccountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AccountSubtype(); ok {
		_spec.SetField(account.FieldAccountSubtype, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ParentAccountID(); ok {
		_spec.SetField(account.FieldParentAccountID, field.TypeUUID, value)
	}
	if _u.mutation.ParentAccountIDCleared() {
		_spec.ClearField(account.FieldParentAccountID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(account.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(account.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Dimensions(); ok {
		_spec.SetField(account.FieldDimensions, field.TypeJSON, value)
	}
	if _u.mutation.DimensionsCleared() {
		_spec.ClearField(account.FieldDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.NormalBalance(); ok {
		_spec.SetField(account.FieldNormalBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHeader(); ok {
		_spec.SetField(account.FieldIsHeader, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(account.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowsDirectPosting(); ok {
		_spec.SetField(account.FieldAllowsDirectPosting, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsTrustAccount(); ok {
		_spec.SetField(account.FieldIsTrustAccount, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrustType(); ok {
		_spec.SetField(account.FieldTrustType, field.TypeString, value)
	}
	if _u.mutation.TrustTypeCleared() {
		_spec.ClearField(account.FieldTrustType, field.TypeString)
	}
	if value, ok := _u.mutation.BudgetAmountAmountCents(); ok {
		_spec.SetField(account.FieldBudgetAmountAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBudgetAmountAmountCents(); ok {
		_spec.AddField(account.FieldBudgetAmountAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.BudgetAmountAmountCentsCleared() {
		_spec.ClearField(account.FieldBudgetAmountAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.BudgetAmountCurrency(); ok {
		_spec.SetField(account.FieldBudgetAmountCurrency, field.TypeString, value)
	}
	if _u.mutation.BudgetAmountCurrencyCleared() {
		_spec.ClearField(account.FieldBudgetAmountCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.TaxLine(); ok {
		_spec.SetField(account.FieldTaxLine, field.TypeString, value)
	}
	if _u.mutation.TaxLineCleared() {
		_spec.ClearField(account.FieldTaxLine, field.TypeString)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BankAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBankAccountsIDs(); len(nodes) > 0 && !_u.mutation.BankAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BankAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountUpdateOne) SetCreatedBy(v string) *AccountUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCreatedBy(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccountUpdateOne) SetUpdatedBy(v string) *AccountUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUpdatedBy(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AccountUpdateOne) SetSource(v account.Source) *AccountUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSource(v *account.Source) *AccountUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *AccountUpdateOne) SetCorrelationID(v string) *AccountUpdateOne {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCorrelationID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *AccountUpdateOne) ClearCorrelationID() *AccountUpdateOne {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *AccountUpdateOne) SetAgentGoalID(v string) *AccountUpdateOne {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAgentGoalID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *AccountUpdateOne) ClearAgentGoalID() *AccountUpdateOne {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetAccountNumber sets the "account_number" field.
func (_u *AccountUpdateOne) SetAccountNumber(v string) *AccountUpdateOne {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccountNumber(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountUpdateOne) SetDescription(v string) *AccountUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDescription(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountUpdateOne) ClearDescription() *AccountUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountUpdateOne) SetAccountType(v account.AccountType) *AccountUpdateOne {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccountType(v *account.AccountType) *AccountUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetAccountSubtype sets the "account_subtype" field.
func (_u *AccountUpdateOne) SetAccountSubtype(v account.AccountSubtype) *AccountUpdateOne {
	_u.mutation.SetAccountSubtype(v)
	return _u
}

// SetNillableAccountSubtype sets the "account_subtype" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccountSubtype(v *account.AccountSubtype) *AccountUpdateOne {
	if v != nil {
		_u.SetAccountSubtype(*v)
	}
	return _u
}

// SetParentAccountID sets the "parent_account_id" field.
func (_u *AccountUpdateOne) SetParentAccountID(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetParentAccountID(v)
	return _u
}

// SetNillableParentAccountID sets the "parent_account_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableParentAccountID(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetParentAccountID(*v)
	}
	return _u
}

// ClearParentAccountID clears the value of the "parent_account_id" field.
func (_u *AccountUpdateOne) ClearParentAccountID() *AccountUpdateOne {
	_u.mutation.ClearParentAccountID()
	return _u
}

// SetDepth sets the "depth" field.
func (_u *AccountUpdateOne) SetDepth(v int) *AccountUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDepth(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *AccountUpdateOne) AddDepth(v int) *AccountUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetDimensions sets the "dimensions" field.
func (_u *AccountUpdateOne) SetDimensions(v *types.AccountDimensions) *AccountUpdateOne {
	_u.mutation.SetDimensions(v)
	return _u
}

// ClearDimensions clears the value of the "dimensions" field.
func (_u *AccountUpdateOne) ClearDimensions() *AccountUpdateOne {
	_u.mutation.ClearDimensions()
	return _u
}

// SetNormalBalance sets the "normal_balance" field.
func (_u *AccountUpdateOne) SetNormalBalance(v string) *AccountUpdateOne {
	_u.mutation.SetNormalBalance(v)
	return _u
}

// SetNillableNormalBalance sets the "normal_balance" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableNormalBalance(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetNormalBalance(*v)
	}
	return _u
}

// SetIsHeader sets the "is_header" field.
func (_u *AccountUpdateOne) SetIsHeader(v bool) *AccountUpdateOne {
	_u.mutation.SetIsHeader(v)
	return _u
}

// SetNillableIsHeader sets the "is_header" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsHeader(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsHeader(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AccountUpdateOne) SetIsSystem(v bool) *AccountUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsSystem(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetAllowsDirectPosting sets the "allows_direct_posting" field.
func (_u *AccountUpdateOne) SetAllowsDirectPosting(v bool) *AccountUpdateOne {
	_u.mutation.SetAllowsDirectPosting(v)
	return _u
}

// SetNillableAllowsDirectPosting sets the "allows_direct_posting" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAllowsDirectPosting(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetAllowsDirectPosting(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdateOne) SetStatus(v account.Status) *AccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableStatus(v *account.Status) *AccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsTrustAccount sets the "is_trust_account" field.
func (_u *AccountUpdateOne) SetIsTrustAccount(v bool) *AccountUpdateOne {
	_u.mutation.SetIsTrustAccount(v)
	return _u
}

// SetNillableIsTrustAccount sets the "is_trust_account" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsTrustAccount(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsTrustAccount(*v)
	}
	return _u
}

// SetTrustType sets the "trust_type" field.
func (_u *AccountUpdateOne) SetTrustType(v string) *AccountUpdateOne {
	_u.mutation.SetTrustType(v)
	return _u
}

// SetNillableTrustType sets the "trust_type" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableTrustType(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetTrustType(*v)
	}
	return _u
}

// ClearTrustType clears the value of the "trust_type" field.
func (_u *AccountUpdateOne) ClearTrustType() *AccountUpdateOne {
	_u.mutation.ClearTrustType()
	return _u
}

// SetBudgetAmountAmountCents sets the "budget_amount_amount_cents" field.
func (_u *AccountUpdateOne) SetBudgetAmountAmountCents(v int64) *AccountUpdateOne {
	_u.mutation.ResetBudgetAmountAmountCents()
	_u.mutation.SetBudgetAmountAmountCents(v)
	return _u
}

// SetNillableBudgetAmountAmountCents sets the "budget_amount_amount_cents" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBudgetAmountAmountCents(v *int64) *AccountUpdateOne {
	if v != nil {
		_u.SetBudgetAmountAmountCents(*v)
	}
	return _u
}

// AddBudgetAmountAmountCents adds value to the "budget_amount_amount_cents" field.
func (_u *AccountUpdateOne) AddBudgetAmountAmountCents(v int64) *AccountUpdateOne {
	_u.mutation.AddBudgetAmountAmountCents(v)
	return _u
}

// ClearBudgetAmountAmountCents clears the value of the "budget_amount_amount_cents" field.
func (_u *AccountUpdateOne) ClearBudgetAmountAmountCents() *AccountUpdateOne {
	_u.mutation.ClearBudgetAmountAmountCents()
	return _u
}

// SetBudgetAmountCurrency sets the "budget_amount_currency" field.
func (_u *AccountUpdateOne) SetBudgetAmountCurrency(v string) *AccountUpdateOne {
	_u.mutation.SetBudgetAmountCurrency(v)
	return _u
}

// SetNillableBudgetAmountCurrency sets the "budget_amount_currency" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBudgetAmountCurrency(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetBudgetAmountCurrency(*v)
	}
	return _u
}

// ClearBudgetAmountCurrency clears the value of the "budget_amount_currency" field.
func (_u *AccountUpdateOne) ClearBudgetAmountCurrency() *AccountUpdateOne {
	_u.mutation.ClearBudgetAmountCurrency()
	return _u
}

// SetTaxLine sets the "tax_line" field.
func (_u *AccountUpdateOne) SetTaxLine(v string) *AccountUpdateOne {
	_u.mutation.SetTaxLine(v)
	return _u
}

// SetNillableTaxLine sets the "tax_line" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableTaxLine(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetTaxLine(*v)
	}
	return _u
}

// ClearTaxLine clears the value of the "tax_line" field.
func (_u *AccountUpdateOne) ClearTaxLine() *AccountUpdateOne {
	_u.mutation.ClearTaxLine()
	return _u
}

// AddChildIDs adds the "children" edge to the Account entity by IDs.
func (_u *AccountUpdateOne) AddChildIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Account entity.
func (_u *AccountUpdateOne) AddChildren(v ...*Account) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Account entity by ID.
func (_u *AccountUpdateOne) SetParentID(id uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Account entity by ID if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableParentID(id *uuid.UUID) *AccountUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Account entity.
func (_u *AccountUpdateOne) SetParent(v *Account) *AccountUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the LedgerEntry entity by IDs.
func (_u *AccountUpdateOne) AddEntryIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the LedgerEntry entity.
func (_u *AccountUpdateOne) AddEntries(v ...*LedgerEntry) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddBankAccountIDs adds the "bank_accounts" edge to the BankAccount entity by IDs.
func (_u *AccountUpdateOne) AddBankAccountIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.AddBankAccountIDs(ids...)
	return _u
}

// AddBankAccounts adds the "bank_accounts" edges to the BankAccount entity.
func (_u *AccountUpdateOne) AddBankAccounts(v ...*BankAccount) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBankAccountIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Account entity.
func (_u *AccountUpdateOne) ClearChildren() *AccountUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Account entities by IDs.
func (_u *AccountUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Account entities.
func (_u *AccountUpdateOne) RemoveChildren(v ...*Account) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Account entity.
func (_u *AccountUpdateOne) ClearParent() *AccountUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearEntries clears all "entries" edges to the LedgerEntry entity.
func (_u *AccountUpdateOne) ClearEntries() *AccountUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to LedgerEntry entities by IDs.
func (_u *AccountUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to LedgerEntry entities.
func (_u *AccountUpdateOne) RemoveEntries(v ...*LedgerEntry) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearBankAccounts clears all "bank_accounts" edges to the BankAccount entity.
func (_u *AccountUpdateOne) ClearBankAccounts() *AccountUpdateOne {
	_u.mutation.ClearBankAccounts()
	return _u
}

// RemoveBankAccountIDs removes the "bank_accounts" edge to BankAccount entities by IDs.
func (_u *AccountUpdateOne) RemoveBankAccountIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.RemoveBankAccountIDs(ids...)
	return _u
}

// RemoveBankAccounts removes "bank_accounts" edges to BankAccount entities.
func (_u *AccountUpdateOne) RemoveBankAccounts(v ...*BankAccount) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBankAccountIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := account.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Account.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := account.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "Account.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := account.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Account.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := account.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "Account.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountSubtype(); ok {
		if err := account.AccountSubtypeValidator(v); err != nil {
			return &ValidationError{Name: "account_subtype", err: fmt.Errorf(`ent: validator failed for field "Account.account_subtype": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BudgetAmountCurrency(); ok {
		if err := account.BudgetAmountCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "budget_amount_currency", err: fmt.Errorf(`ent: validator failed for field "Account.budget_amount_currency": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(account.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(account.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(account.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(account.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(account.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(account.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(account.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(account.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(account.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(account.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(account.FieldAccountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AccountSubtype(); ok {
		_spec.SetField(account.FieldAccountSubtype, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ParentAccountID(); ok {
		_spec.SetField(account.FieldParentAccountID, field.TypeUUID, value)
	}
	if _u.mutation.ParentAccountIDCleared() {
		_spec.ClearField(account.FieldParentAccountID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(account.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(account.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Dimensions(); ok {
		_spec.SetField(account.FieldDimensions, field.TypeJSON, value)
	}
	if _u.mutation.DimensionsCleared() {
		_spec.ClearField(account.FieldDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.NormalBalance(); ok {
		_spec.SetField(account.FieldNormalBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsHeader(); ok {
		_spec.SetField(account.FieldIsHeader, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(account.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowsDirectPosting(); ok {
		_spec.SetField(account.FieldAllowsDirectPosting, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsTrustAccount(); ok {
		_spec.SetField(account.FieldIsTrustAccount, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrustType(); ok {
		_spec.SetField(account.FieldTrustType, field.TypeString, value)
	}
	if _u.mutation.TrustTypeCleared() {
		_spec.ClearField(account.FieldTrustType, field.TypeString)
	}
	if value, ok := _u.mutation.BudgetAmountAmountCents(); ok {
		_spec.SetField(account.FieldBudgetAmountAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBudgetAmountAmountCents(); ok {
		_spec.AddField(account.FieldBudgetAmountAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.BudgetAmountAmountCentsCleared() {
		_spec.ClearField(account.FieldBudgetAmountAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.BudgetAmountCurrency(); ok {
		_spec.SetField(account.FieldBudgetAmountCurrency, field.TypeString, value)
	}
	if _u.mutation.BudgetAmountCurrencyCleared() {
		_spec.ClearField(account.FieldBudgetAmountCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.TaxLine(); ok {
		_spec.SetField(account.FieldTaxLine, field.TypeString, value)
	}
	if _u.mutation.TaxLineCleared() {
		_spec.ClearField(account.FieldTaxLine, field.TypeString)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EntriesTable,
			Columns: []string{account.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BankAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBankAccountsIDs(); len(nodes) > 0 && !_u.mutation.BankAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BankAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.BankAccountsTable,
			Columns: []string{account.BankAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
