// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/account"
	"github.com/matthewbaird/ontology/ent/bankaccount"
	"github.com/matthewbaird/ontology/ent/portfolio"
	"github.com/matthewbaird/ontology/ent/predicate"
	"github.com/matthewbaird/ontology/ent/property"
	"github.com/matthewbaird/ontology/ent/reconciliation"
)

// BankAccountUpdate is the builder for updating BankAccount entities.
type BankAccountUpdate struct {
	config
	hooks    []Hook
	mutation *BankAccountMutation
}

// Where appends a list predicates to the BankAccountUpdate builder.
func (_u *BankAccountUpdate) Where(ps ...predicate.BankAccount) *BankAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BankAccountUpdate) SetUpdatedAt(v time.Time) *BankAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BankAccountUpdate) SetCreatedBy(v string) *BankAccountUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableCreatedBy(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BankAccountUpdate) SetUpdatedBy(v string) *BankAccountUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableUpdatedBy(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *BankAccountUpdate) SetSource(v bankaccount.Source) *BankAccountUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableSource(v *bankaccount.Source) *BankAccountUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *BankAccountUpdate) SetCorrelationID(v string) *BankAccountUpdate {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableCorrelationID(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *BankAccountUpdate) ClearCorrelationID() *BankAccountUpdate {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *BankAccountUpdate) SetAgentGoalID(v string) *BankAccountUpdate {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableAgentGoalID(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *BankAccountUpdate) ClearAgentGoalID() *BankAccountUpdate {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetName sets the "name" field.
func (_u *BankAccountUpdate) SetName(v string) *BankAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableName(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *BankAccountUpdate) SetAccountType(v bankaccount.AccountType) *BankAccountUpdate {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableAccountType(v *bankaccount.AccountType) *BankAccountUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *BankAccountUpdate) SetBankName(v string) *BankAccountUpdate {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableBankName(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// SetRoutingNumber sets the "routing_number" field.
func (_u *BankAccountUpdate) SetRoutingNumber(v string) *BankAccountUpdate {
	_u.mutation.SetRoutingNumber(v)
	return _u
}

// SetNillableRoutingNumber sets the "routing_number" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableRoutingNumber(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetRoutingNumber(*v)
	}
	return _u
}

// ClearRoutingNumber clears the value of the "routing_number" field.
func (_u *BankAccountUpdate) ClearRoutingNumber() *BankAccountUpdate {
	_u.mutation.ClearRoutingNumber()
	return _u
}

// SetAccountNumberLastFour sets the "account_number_last_four" field.
func (_u *BankAccountUpdate) SetAccountNumberLastFour(v string) *BankAccountUpdate {
	_u.mutation.SetAccountNumberLastFour(v)
	return _u
}

// SetNillableAccountNumberLastFour sets the "account_number_last_four" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableAccountNumberLastFour(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetAccountNumberLastFour(*v)
	}
	return _u
}

// SetPropertyID sets the "property_id" field.
func (_u *BankAccountUpdate) SetPropertyID(v string) *BankAccountUpdate {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillablePropertyID(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// ClearPropertyID clears the value of the "property_id" field.
func (_u *BankAccountUpdate) ClearPropertyID() *BankAccountUpdate {
	_u.mutation.ClearPropertyID()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *BankAccountUpdate) SetEntityID(v string) *BankAccountUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableEntityID(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *BankAccountUpdate) ClearEntityID() *BankAccountUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BankAccountUpdate) SetStatus(v bankaccount.Status) *BankAccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableStatus(v *bankaccount.Status) *BankAccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentBalanceAmountCents sets the "current_balance_amount_cents" field.
func (_u *BankAccountUpdate) SetCurrentBalanceAmountCents(v int64) *BankAccountUpdate {
	_u.mutation.ResetCurrentBalanceAmountCents()
	_u.mutation.SetCurrentBalanceAmountCents(v)
	return _u
}

// SetNillableCurrentBalanceAmountCents sets the "current_balance_amount_cents" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableCurrentBalanceAmountCents(v *int64) *BankAccountUpdate {
	if v != nil {
		_u.SetCurrentBalanceAmountCents(*v)
	}
	return _u
}

// AddCurrentBalanceAmountCents adds value to the "current_balance_amount_cents" field.
func (_u *BankAccountUpdate) AddCurrentBalanceAmountCents(v int64) *BankAccountUpdate {
	_u.mutation.AddCurrentBalanceAmountCents(v)
	return _u
}

// ClearCurrentBalanceAmountCents clears the value of the "current_balance_amount_cents" field.
func (_u *BankAccountUpdate) ClearCurrentBalanceAmountCents() *BankAccountUpdate {
	_u.mutation.ClearCurrentBalanceAmountCents()
	return _u
}

// SetCurrentBalanceCurrency sets the "current_balance_currency" field.
func (_u *BankAccountUpdate) SetCurrentBalanceCurrency(v string) *BankAccountUpdate {
	_u.mutation.SetCurrentBalanceCurrency(v)
	return _u
}

// SetNillableCurrentBalanceCurrency sets the "current_balance_currency" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableCurrentBalanceCurrency(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetCurrentBalanceCurrency(*v)
	}
	return _u
}

// ClearCurrentBalanceCurrency clears the value of the "current_balance_currency" field.
func (_u *BankAccountUpdate) ClearCurrentBalanceCurrency() *BankAccountUpdate {
	_u.mutation.ClearCurrentBalanceCurrency()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *BankAccountUpdate) SetLastReconciledAt(v time.Time) *BankAccountUpdate {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableLastReconciledAt(v *time.Time) *BankAccountUpdate {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *BankAccountUpdate) ClearLastReconciledAt() *BankAccountUpdate {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetIsTrust sets the "is_trust" field.
func (_u *BankAccountUpdate) SetIsTrust(v bool) *BankAccountUpdate {
	_u.mutation.SetIsTrust(v)
	return _u
}

// SetNillableIsTrust sets the "is_trust" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableIsTrust(v *bool) *BankAccountUpdate {
	if v != nil {
		_u.SetIsTrust(*v)
	}
	return _u
}

// SetTrustState sets the "trust_state" field.
func (_u *BankAccountUpdate) SetTrustState(v string) *BankAccountUpdate {
	_u.mutation.SetTrustState(v)
	return _u
}

// SetNillableTrustState sets the "trust_state" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableTrustState(v *string) *BankAccountUpdate {
	if v != nil {
		_u.SetTrustState(*v)
	}
	return _u
}

// ClearTrustState clears the value of the "trust_state" field.
func (_u *BankAccountUpdate) ClearTrustState() *BankAccountUpdate {
	_u.mutation.ClearTrustState()
	return _u
}

// SetComminglingAllowed sets the "commingling_allowed" field.
func (_u *BankAccountUpdate) SetComminglingAllowed(v bool) *BankAccountUpdate {
	_u.mutation.SetComminglingAllowed(v)
	return _u
}

// SetNillableComminglingAllowed sets the "commingling_allowed" field if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableComminglingAllowed(v *bool) *BankAccountUpdate {
	if v != nil {
		_u.SetComminglingAllowed(*v)
	}
	return _u
}

// SetTrustPortfolioID sets the "trust_portfolio" edge to the Portfolio entity by ID.
func (_u *BankAccountUpdate) SetTrustPortfolioID(id uuid.UUID) *BankAccountUpdate {
	_u.mutation.SetTrustPortfolioID(id)
	return _u
}

// SetNillableTrustPortfolioID sets the "trust_portfolio" edge to the Portfolio entity by ID if the given value is not nil.
func (_u *BankAccountUpdate) SetNillableTrustPortfolioID(id *uuid.UUID) *BankAccountUpdate {
	if id != nil {
		_u = _u.SetTrustPortfolioID(*id)
	}
	return _u
}

// SetTrustPortfolio sets the "trust_portfolio" edge to the Portfolio entity.
func (_u *BankAccountUpdate) SetTrustPortfolio(v *Portfolio) *BankAccountUpdate {
	return _u.SetTrustPortfolioID(v.ID)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (_u *BankAccountUpdate) AddPropertyIDs(ids ...uuid.UUID) *BankAccountUpdate {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the Property entity.
func (_u *BankAccountUpdate) AddProperties(v ...*Property) *BankAccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// SetGlAccountID sets the "gl_account" edge to the Account entity by ID.
func (_u *BankAccountUpdate) SetGlAccountID(id uuid.UUID) *BankAccountUpdate {
	_u.mutation.SetGlAccountID(id)
	return _u
}

// SetGlAccount sets the "gl_account" edge to the Account entity.
func (_u *BankAccountUpdate) SetGlAccount(v *Account) *BankAccountUpdate {
	return _u.SetGlAccountID(v.ID)
}

// AddReconciliationIDs adds the "reconciliations" edge to the Reconciliation entity by IDs.
func (_u *BankAccountUpdate) AddReconciliationIDs(ids ...uuid.UUID) *BankAccountUpdate {
	_u.mutation.AddReconciliationIDs(ids...)
	return _u
}

// AddReconciliations adds the "reconciliations" edges to the Reconciliation entity.
func (_u *BankAccountUpdate) AddReconciliations(v ...*Reconciliation) *BankAccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReconciliationIDs(ids...)
}

// Mutation returns the BankAccountMutation object of the builder.
func (_u *BankAccountUpdate) Mutation() *BankAccountMutation {
	return _u.mutation
}

// ClearTrustPortfolio clears the "trust_portfolio" edge to the Portfolio entity.
func (_u *BankAccountUpdate) ClearTrustPortfolio() *BankAccountUpdate {
	_u.mutation.ClearTrustPortfolio()
	return _u
}

// ClearProperties clears all "properties" edges to the Property entity.
func (_u *BankAccountUpdate) ClearProperties() *BankAccountUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (_u *BankAccountUpdate) RemovePropertyIDs(ids ...uuid.UUID) *BankAccountUpdate {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to Property entities.
func (_u *BankAccountUpdate) RemoveProperties(v ...*Property) *BankAccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// ClearGlAccount clears the "gl_account" edge to the Account entity.
func (_u *BankAccountUpdate) ClearGlAccount() *BankAccountUpdate {
	_u.mutation.ClearGlAccount()
	return _u
}

// ClearReconciliations clears all "reconciliations" edges to the Reconciliation entity.
func (_u *BankAccountUpdate) ClearReconciliations() *BankAccountUpdate {
	_u.mutation.ClearReconciliations()
	return _u
}

// RemoveReconciliationIDs removes the "reconciliations" edge to Reconciliation entities by IDs.
func (_u *BankAccountUpdate) RemoveReconciliationIDs(ids ...uuid.UUID) *BankAccountUpdate {
	_u.mutation.RemoveReconciliationIDs(ids...)
	return _u
}

// RemoveReconciliations removes "reconciliations" edges to Reconciliation entities.
func (_u *BankAccountUpdate) RemoveReconciliations(v ...*Reconciliation) *BankAccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReconciliationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BankAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BankAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BankAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BankAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BankAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bankaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BankAccountUpdate) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := bankaccount.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BankAccount.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := bankaccount.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "BankAccount.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := bankaccount.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "BankAccount.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := bankaccount.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "BankAccount.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bankaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BankAccount.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentBalanceCurrency(); ok {
		if err := bankaccount.CurrentBalanceCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "current_balance_currency", err: fmt.Errorf(`ent: validator failed for field "BankAccount.current_balance_currency": %w`, err)}
		}
	}
	if _u.mutation.GlAccountCleared() && len(_u.mutation.GlAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BankAccount.gl_account"`)
	}
	return nil
}

func (_u *BankAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bankaccount.Table, bankaccount.Columns, sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bankaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bankaccount.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bankaccount.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(bankaccount.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(bankaccount.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(bankaccount.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(bankaccount.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(bankaccount.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bankaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(bankaccount.FieldAccountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(bankaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingNumber(); ok {
		_spec.SetField(bankaccount.FieldRoutingNumber, field.TypeString, value)
	}
	if _u.mutation.RoutingNumberCleared() {
		_spec.ClearField(bankaccount.FieldRoutingNumber, field.TypeString)
	}
	if value, ok := _u.mutation.AccountNumberLastFour(); ok {
		_spec.SetField(bankaccount.FieldAccountNumberLastFour, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertyID(); ok {
		_spec.SetField(bankaccount.FieldPropertyID, field.TypeString, value)
	}
	if _u.mutation.PropertyIDCleared() {
		_spec.ClearField(bankaccount.FieldPropertyID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(bankaccount.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(bankaccount.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bankaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentBalanceAmountCents(); ok {
		_spec.SetField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrentBalanceAmountCents(); ok {
		_spec.AddField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.CurrentBalanceAmountCentsCleared() {
		_spec.ClearField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.CurrentBalanceCurrency(); ok {
		_spec.SetField(bankaccount.FieldCurrentBalanceCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrentBalanceCurrencyCleared() {
		_spec.ClearField(bankaccount.FieldCurrentBalanceCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(bankaccount.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(bankaccount.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsTrust(); ok {
		_spec.SetField(bankaccount.FieldIsTrust, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrustState(); ok {
		_spec.SetField(bankaccount.FieldTrustState, field.TypeString, value)
	}
	if _u.mutation.TrustStateCleared() {
		_spec.ClearField(bankaccount.FieldTrustState, field.TypeString)
	}
	if value, ok := _u.mutation.ComminglingAllowed(); ok {
		_spec.SetField(bankaccount.FieldComminglingAllowed, field.TypeBool, value)
	}
	if _u.mutation.TrustPortfolioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bankaccount.TrustPortfolioTable,
			Columns: []string{bankaccount.TrustPortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrustPortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bankaccount.TrustPortfolioTable,
			Columns: []string{bankaccount.TrustPortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GlAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   bankaccount.GlAccountTable,
			Columns: []string{bankaccount.GlAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GlAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   bankaccount.GlAccountTable,
			Columns: []string{bankaccount.GlAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReconciliationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReconciliationsIDs(); len(nodes) > 0 && !_u.mutation.ReconciliationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReconciliationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BankAccountUpdateOne is the builder for updating a single BankAccount entity.
type BankAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BankAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BankAccountUpdateOne) SetUpdatedAt(v time.Time) *BankAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BankAccountUpdateOne) SetCreatedBy(v string) *BankAccountUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableCreatedBy(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BankAccountUpdateOne) SetUpdatedBy(v string) *BankAccountUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableUpdatedBy(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *BankAccountUpdateOne) SetSource(v bankaccount.Source) *BankAccountUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableSource(v *bankaccount.Source) *BankAccountUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *BankAccountUpdateOne) SetCorrelationID(v string) *BankAccountUpdateOne {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableCorrelationID(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *BankAccountUpdateOne) ClearCorrelationID() *BankAccountUpdateOne {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *BankAccountUpdateOne) SetAgentGoalID(v string) *BankAccountUpdateOne {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableAgentGoalID(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *BankAccountUpdateOne) ClearAgentGoalID() *BankAccountUpdateOne {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetName sets the "name" field.
func (_u *BankAccountUpdateOne) SetName(v string) *BankAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableName(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *BankAccountUpdateOne) SetAccountType(v bankaccount.AccountType) *BankAccountUpdateOne {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableAccountType(v *bankaccount.AccountType) *BankAccountUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *BankAccountUpdateOne) SetBankName(v string) *BankAccountUpdateOne {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableBankName(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// SetRoutingNumber sets the "routing_number" field.
func (_u *BankAccountUpdateOne) SetRoutingNumber(v string) *BankAccountUpdateOne {
	_u.mutation.SetRoutingNumber(v)
	return _u
}

// SetNillableRoutingNumber sets the "routing_number" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableRoutingNumber(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetRoutingNumber(*v)
	}
	return _u
}

// ClearRoutingNumber clears the value of the "routing_number" field.
func (_u *BankAccountUpdateOne) ClearRoutingNumber() *BankAccountUpdateOne {
	_u.mutation.ClearRoutingNumber()
	return _u
}

// SetAccountNumberLastFour sets the "account_number_last_four" field.
func (_u *BankAccountUpdateOne) SetAccountNumberLastFour(v string) *BankAccountUpdateOne {
	_u.mutation.SetAccountNumberLastFour(v)
	return _u
}

// SetNillableAccountNumberLastFour sets the "account_number_last_four" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableAccountNumberLastFour(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetAccountNumberLastFour(*v)
	}
	return _u
}

// SetPropertyID sets the "property_id" field.
func (_u *BankAccountUpdateOne) SetPropertyID(v string) *BankAccountUpdateOne {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillablePropertyID(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// ClearPropertyID clears the value of the "property_id" field.
func (_u *BankAccountUpdateOne) ClearPropertyID() *BankAccountUpdateOne {
	_u.mutation.ClearPropertyID()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *BankAccountUpdateOne) SetEntityID(v string) *BankAccountUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableEntityID(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *BankAccountUpdateOne) ClearEntityID() *BankAccountUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BankAccountUpdateOne) SetStatus(v bankaccount.Status) *BankAccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableStatus(v *bankaccount.Status) *BankAccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentBalanceAmountCents sets the "current_balance_amount_cents" field.
func (_u *BankAccountUpdateOne) SetCurrentBalanceAmountCents(v int64) *BankAccountUpdateOne {
	_u.mutation.ResetCurrentBalanceAmountCents()
	_u.mutation.SetCurrentBalanceAmountCents(v)
	return _u
}

// SetNillableCurrentBalanceAmountCents sets the "current_balance_amount_cents" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableCurrentBalanceAmountCents(v *int64) *BankAccountUpdateOne {
	if v != nil {
		_u.SetCurrentBalanceAmountCents(*v)
	}
	return _u
}

// AddCurrentBalanceAmountCents adds value to the "current_balance_amount_cents" field.
func (_u *BankAccountUpdateOne) AddCurrentBalanceAmountCents(v int64) *BankAccountUpdateOne {
	_u.mutation.AddCurrentBalanceAmountCents(v)
	return _u
}

// ClearCurrentBalanceAmountCents clears the value of the "current_balance_amount_cents" field.
func (_u *BankAccountUpdateOne) ClearCurrentBalanceAmountCents() *BankAccountUpdateOne {
	_u.mutation.ClearCurrentBalanceAmountCents()
	return _u
}

// SetCurrentBalanceCurrency sets the "current_balance_currency" field.
func (_u *BankAccountUpdateOne) SetCurrentBalanceCurrency(v string) *BankAccountUpdateOne {
	_u.mutation.SetCurrentBalanceCurrency(v)
	return _u
}

// SetNillableCurrentBalanceCurrency sets the "current_balance_currency" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableCurrentBalanceCurrency(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetCurrentBalanceCurrency(*v)
	}
	return _u
}

// ClearCurrentBalanceCurrency clears the value of the "current_balance_currency" field.
func (_u *BankAccountUpdateOne) ClearCurrentBalanceCurrency() *BankAccountUpdateOne {
	_u.mutation.ClearCurrentBalanceCurrency()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *BankAccountUpdateOne) SetLastReconciledAt(v time.Time) *BankAccountUpdateOne {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableLastReconciledAt(v *time.Time) *BankAccountUpdateOne {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *BankAccountUpdateOne) ClearLastReconciledAt() *BankAccountUpdateOne {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetIsTrust sets the "is_trust" field.
func (_u *BankAccountUpdateOne) SetIsTrust(v bool) *BankAccountUpdateOne {
	_u.mutation.SetIsTrust(v)
	return _u
}

// SetNillableIsTrust sets the "is_trust" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableIsTrust(v *bool) *BankAccountUpdateOne {
	if v != nil {
		_u.SetIsTrust(*v)
	}
	return _u
}

// SetTrustState sets the "trust_state" field.
func (_u *BankAccountUpdateOne) SetTrustState(v string) *BankAccountUpdateOne {
	_u.mutation.SetTrustState(v)
	return _u
}

// SetNillableTrustState sets the "trust_state" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableTrustState(v *string) *BankAccountUpdateOne {
	if v != nil {
		_u.SetTrustState(*v)
	}
	return _u
}

// ClearTrustState clears the value of the "trust_state" field.
func (_u *BankAccountUpdateOne) ClearTrustState() *BankAccountUpdateOne {
	_u.mutation.ClearTrustState()
	return _u
}

// SetComminglingAllowed sets the "commingling_allowed" field.
func (_u *BankAccountUpdateOne) SetComminglingAllowed(v bool) *BankAccountUpdateOne {
	_u.mutation.SetComminglingAllowed(v)
	return _u
}

// SetNillableComminglingAllowed sets the "commingling_allowed" field if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableComminglingAllowed(v *bool) *BankAccountUpdateOne {
	if v != nil {
		_u.SetComminglingAllowed(*v)
	}
	return _u
}

// SetTrustPortfolioID sets the "trust_portfolio" edge to the Portfolio entity by ID.
func (_u *BankAccountUpdateOne) SetTrustPortfolioID(id uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.SetTrustPortfolioID(id)
	return _u
}

// SetNillableTrustPortfolioID sets the "trust_portfolio" edge to the Portfolio entity by ID if the given value is not nil.
func (_u *BankAccountUpdateOne) SetNillableTrustPortfolioID(id *uuid.UUID) *BankAccountUpdateOne {
	if id != nil {
		_u = _u.SetTrustPortfolioID(*id)
	}
	return _u
}

// SetTrustPortfolio sets the "trust_portfolio" edge to the Portfolio entity.
func (_u *BankAccountUpdateOne) SetTrustPortfolio(v *Portfolio) *BankAccountUpdateOne {
	return _u.SetTrustPortfolioID(v.ID)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (_u *BankAccountUpdateOne) AddPropertyIDs(ids ...uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.AddPropertyIDs(ids...)
	return _u
}

// AddProperties adds the "properties" edges to the Property entity.
func (_u *BankAccountUpdateOne) AddProperties(v ...*Property) *BankAccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyIDs(ids...)
}

// SetGlAccountID sets the "gl_account" edge to the Account entity by ID.
func (_u *BankAccountUpdateOne) SetGlAccountID(id uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.SetGlAccountID(id)
	return _u
}

// SetGlAccount sets the "gl_account" edge to the Account entity.
func (_u *BankAccountUpdateOne) SetGlAccount(v *Account) *BankAccountUpdateOne {
	return _u.SetGlAccountID(v.ID)
}

// AddReconciliationIDs adds the "reconciliations" edge to the Reconciliation entity by IDs.
func (_u *BankAccountUpdateOne) AddReconciliationIDs(ids ...uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.AddReconciliationIDs(ids...)
	return _u
}

// AddReconciliations adds the "reconciliations" edges to the Reconciliation entity.
func (_u *BankAccountUpdateOne) AddReconciliations(v ...*Reconciliation) *BankAccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReconciliationIDs(ids...)
}

// Mutation returns the BankAccountMutation object of the builder.
func (_u *BankAccountUpdateOne) Mutation() *BankAccountMutation {
	return _u.mutation
}

// ClearTrustPortfolio clears the "trust_portfolio" edge to the Portfolio entity.
func (_u *BankAccountUpdateOne) ClearTrustPortfolio() *BankAccountUpdateOne {
	_u.mutation.ClearTrustPortfolio()
	return _u
}

// ClearProperties clears all "properties" edges to the Property entity.
func (_u *BankAccountUpdateOne) ClearProperties() *BankAccountUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (_u *BankAccountUpdateOne) RemovePropertyIDs(ids ...uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.RemovePropertyIDs(ids...)
	return _u
}

// RemoveProperties removes "properties" edges to Property entities.
func (_u *BankAccountUpdateOne) RemoveProperties(v ...*Property) *BankAccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyIDs(ids...)
}

// ClearGlAccount clears the "gl_account" edge to the Account entity.
func (_u *BankAccountUpdateOne) ClearGlAccount() *BankAccountUpdateOne {
	_u.mutation.ClearGlAccount()
	return _u
}

// ClearReconciliations clears all "reconciliations" edges to the Reconciliation entity.
func (_u *BankAccountUpdateOne) ClearReconciliations() *BankAccountUpdateOne {
	_u.mutation.ClearReconciliations()
	return _u
}

// RemoveReconciliationIDs removes the "reconciliations" edge to Reconciliation entities by IDs.
func (_u *BankAccountUpdateOne) RemoveReconciliationIDs(ids ...uuid.UUID) *BankAccountUpdateOne {
	_u.mutation.RemoveReconciliationIDs(ids...)
	return _u
}

// RemoveReconciliations removes "reconciliations" edges to Reconciliation entities.
func (_u *BankAccountUpdateOne) RemoveReconciliations(v ...*Reconciliation) *BankAccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReconciliationIDs(ids...)
}

// Where appends a list predicates to the BankAccountUpdate builder.
func (_u *BankAccountUpdateOne) Where(ps ...predicate.BankAccount) *BankAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BankAccountUpdateOne) Select(field string, fields ...string) *BankAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BankAccount entity.
func (_u *BankAccountUpdateOne) Save(ctx context.Context) (*BankAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BankAccountUpdateOne) SaveX(ctx context.Context) *BankAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BankAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BankAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BankAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bankaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BankAccountUpdateOne) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := bankaccount.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BankAccount.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := bankaccount.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "BankAccount.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := bankaccount.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "BankAccount.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := bankaccount.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "BankAccount.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bankaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BankAccount.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentBalanceCurrency(); ok {
		if err := bankaccount.CurrentBalanceCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "current_balance_currency", err: fmt.Errorf(`ent: validator failed for field "BankAccount.current_balance_currency": %w`, err)}
		}
	}
	if _u.mutation.GlAccountCleared() && len(_u.mutation.GlAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BankAccount.gl_account"`)
	}
	return nil
}

func (_u *BankAccountUpdateOne) sqlSave(ctx context.Context) (_node *BankAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bankaccount.Table, bankaccount.Columns, sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BankAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bankaccount.FieldID)
		for _, f := range fields {
			if !bankaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bankaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bankaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bankaccount.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bankaccount.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(bankaccount.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(bankaccount.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(bankaccount.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(bankaccount.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(bankaccount.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bankaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(bankaccount.FieldAccountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(bankaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutingNumber(); ok {
		_spec.SetField(bankaccount.FieldRoutingNumber, field.TypeString, value)
	}
	if _u.mutation.RoutingNumberCleared() {
		_spec.ClearField(bankaccount.FieldRoutingNumber, field.TypeString)
	}
	if value, ok := _u.mutation.AccountNumberLastFour(); ok {
		_spec.SetField(bankaccount.FieldAccountNumberLastFour, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertyID(); ok {
		_spec.SetField(bankaccount.FieldPropertyID, field.TypeString, value)
	}
	if _u.mutation.PropertyIDCleared() {
		_spec.ClearField(bankaccount.FieldPropertyID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(bankaccount.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(bankaccount.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bankaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentBalanceAmountCents(); ok {
		_spec.SetField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrentBalanceAmountCents(); ok {
		_spec.AddField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.CurrentBalanceAmountCentsCleared() {
		_spec.ClearField(bankaccount.FieldCurrentBalanceAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.CurrentBalanceCurrency(); ok {
		_spec.SetField(bankaccount.FieldCurrentBalanceCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrentBalanceCurrencyCleared() {
		_spec.ClearField(bankaccount.FieldCurrentBalanceCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(bankaccount.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(bankaccount.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsTrust(); ok {
		_spec.SetField(bankaccount.FieldIsTrust, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrustState(); ok {
		_spec.SetField(bankaccount.FieldTrustState, field.TypeString, value)
	}
	if _u.mutation.TrustStateCleared() {
		_spec.ClearField(bankaccount.FieldTrustState, field.TypeString)
	}
	if value, ok := _u.mutation.ComminglingAllowed(); ok {
		_spec.SetField(bankaccount.FieldComminglingAllowed, field.TypeBool, value)
	}
	if _u.mutation.TrustPortfolioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bankaccount.TrustPortfolioTable,
			Columns: []string{bankaccount.TrustPortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrustPortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bankaccount.TrustPortfolioTable,
			Columns: []string{bankaccount.TrustPortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !_u.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.PropertiesTable,
			Columns: []string{bankaccount.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GlAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   bankaccount.GlAccountTable,
			Columns: []string{bankaccount.GlAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GlAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   bankaccount.GlAccountTable,
			Columns: []string{bankaccount.GlAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReconciliationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReconciliationsIDs(); len(nodes) > 0 && !_u.mutation.ReconciliationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReconciliationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bankaccount.ReconciliationsTable,
			Columns: []string{bankaccount.ReconciliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BankAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
