// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matthewbaird/ontology/ent/baseentity"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// BaseEntityDelete is the builder for deleting a BaseEntity entity.
type BaseEntityDelete struct {
	config
	hooks    []Hook
	mutation *BaseEntityMutation
}

// Where appends a list predicates to the BaseEntityDelete builder.
func (_d *BaseEntityDelete) Where(ps ...predicate.BaseEntity) *BaseEntityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BaseEntityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BaseEntityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BaseEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(baseentity.Table, sqlgraph.NewFieldSpec(baseentity.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BaseEntityDeleteOne is the builder for deleting a single BaseEntity entity.
type BaseEntityDeleteOne struct {
	_d *BaseEntityDelete
}

// Where appends a list predicates to the BaseEntityDelete builder.
func (_d *BaseEntityDeleteOne) Where(ps ...predicate.BaseEntity) *BaseEntityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BaseEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{baseentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BaseEntityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
