// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/immutableentity"
)

// ImmutableEntity is the model entity for the ImmutableEntity schema.
type ImmutableEntity struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// When the entity was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the entity was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// User ID, agent ID, or 'system' who created this entity
	CreatedBy string `json:"created_by,omitempty"`
	// User ID, agent ID, or 'system' who last updated this entity
	UpdatedBy string `json:"updated_by,omitempty"`
	// Origin of the change
	Source immutableentity.Source `json:"source,omitempty"`
	// Links related changes across entities
	CorrelationID *string `json:"correlation_id,omitempty"`
	// If source == 'agent', which goal triggered this change
	AgentGoalID  *string `json:"agent_goal_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImmutableEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case immutableentity.FieldCreatedBy, immutableentity.FieldUpdatedBy, immutableentity.FieldSource, immutableentity.FieldCorrelationID, immutableentity.FieldAgentGoalID:
			values[i] = new(sql.NullString)
		case immutableentity.FieldCreatedAt, immutableentity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case immutableentity.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImmutableEntity fields.
func (_m *ImmutableEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case immutableentity.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case immutableentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case immutableentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case immutableentity.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case immutableentity.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case immutableentity.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = immutableentity.Source(value.String)
			}
		case immutableentity.FieldCorrelationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correlation_id", values[i])
			} else if value.Valid {
				_m.CorrelationID = new(string)
				*_m.CorrelationID = value.String
			}
		case immutableentity.FieldAgentGoalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_goal_id", values[i])
			} else if value.Valid {
				_m.AgentGoalID = new(string)
				*_m.AgentGoalID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImmutableEntity.
// This includes values selected through modifiers, order, etc.
func (_m *ImmutableEntity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImmutableEntity.
// Note that you need to call ImmutableEntity.Unwrap() before calling this method if this ImmutableEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImmutableEntity) Update() *ImmutableEntityUpdateOne {
	return NewImmutableEntityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImmutableEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImmutableEntity) Unwrap() *ImmutableEntity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImmutableEntity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImmutableEntity) String() string {
	var builder strings.Builder
	builder.WriteString("ImmutableEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	if v := _m.CorrelationID; v != nil {
		builder.WriteString("correlation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AgentGoalID; v != nil {
		builder.WriteString("agent_goal_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImmutableEntities is a parsable slice of ImmutableEntity.
type ImmutableEntities []*ImmutableEntity
