// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/lease"
	"github.com/matthewbaird/ontology/ent/leasespace"
	"github.com/matthewbaird/ontology/ent/predicate"
	"github.com/matthewbaird/ontology/ent/space"
	"github.com/matthewbaird/ontology/internal/types"
)

// LeaseSpaceUpdate is the builder for updating LeaseSpace entities.
type LeaseSpaceUpdate struct {
	config
	hooks    []Hook
	mutation *LeaseSpaceMutation
}

// Where appends a list predicates to the LeaseSpaceUpdate builder.
func (_u *LeaseSpaceUpdate) Where(ps ...predicate.LeaseSpace) *LeaseSpaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LeaseSpaceUpdate) SetUpdatedAt(v time.Time) *LeaseSpaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LeaseSpaceUpdate) SetCreatedBy(v string) *LeaseSpaceUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableCreatedBy(v *string) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *LeaseSpaceUpdate) SetUpdatedBy(v string) *LeaseSpaceUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableUpdatedBy(v *string) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *LeaseSpaceUpdate) SetSource(v leasespace.Source) *LeaseSpaceUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableSource(v *leasespace.Source) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *LeaseSpaceUpdate) SetCorrelationID(v string) *LeaseSpaceUpdate {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableCorrelationID(v *string) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *LeaseSpaceUpdate) ClearCorrelationID() *LeaseSpaceUpdate {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *LeaseSpaceUpdate) SetAgentGoalID(v string) *LeaseSpaceUpdate {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableAgentGoalID(v *string) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *LeaseSpaceUpdate) ClearAgentGoalID() *LeaseSpaceUpdate {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *LeaseSpaceUpdate) SetIsPrimary(v bool) *LeaseSpaceUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableIsPrimary(v *bool) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetRelationship sets the "relationship" field.
func (_u *LeaseSpaceUpdate) SetRelationship(v leasespace.Relationship) *LeaseSpaceUpdate {
	_u.mutation.SetRelationship(v)
	return _u
}

// SetNillableRelationship sets the "relationship" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableRelationship(v *leasespace.Relationship) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetRelationship(*v)
	}
	return _u
}

// SetEffective sets the "effective" field.
func (_u *LeaseSpaceUpdate) SetEffective(v *types.DateRange) *LeaseSpaceUpdate {
	_u.mutation.SetEffective(v)
	return _u
}

// SetSquareFootageLeased sets the "square_footage_leased" field.
func (_u *LeaseSpaceUpdate) SetSquareFootageLeased(v float64) *LeaseSpaceUpdate {
	_u.mutation.ResetSquareFootageLeased()
	_u.mutation.SetSquareFootageLeased(v)
	return _u
}

// SetNillableSquareFootageLeased sets the "square_footage_leased" field if the given value is not nil.
func (_u *LeaseSpaceUpdate) SetNillableSquareFootageLeased(v *float64) *LeaseSpaceUpdate {
	if v != nil {
		_u.SetSquareFootageLeased(*v)
	}
	return _u
}

// AddSquareFootageLeased adds value to the "square_footage_leased" field.
func (_u *LeaseSpaceUpdate) AddSquareFootageLeased(v float64) *LeaseSpaceUpdate {
	_u.mutation.AddSquareFootageLeased(v)
	return _u
}

// ClearSquareFootageLeased clears the value of the "square_footage_leased" field.
func (_u *LeaseSpaceUpdate) ClearSquareFootageLeased() *LeaseSpaceUpdate {
	_u.mutation.ClearSquareFootageLeased()
	return _u
}

// SetLeaseID sets the "lease" edge to the Lease entity by ID.
func (_u *LeaseSpaceUpdate) SetLeaseID(id uuid.UUID) *LeaseSpaceUpdate {
	_u.mutation.SetLeaseID(id)
	return _u
}

// SetLease sets the "lease" edge to the Lease entity.
func (_u *LeaseSpaceUpdate) SetLease(v *Lease) *LeaseSpaceUpdate {
	return _u.SetLeaseID(v.ID)
}

// SetSpaceID sets the "space" edge to the Space entity by ID.
func (_u *LeaseSpaceUpdate) SetSpaceID(id uuid.UUID) *LeaseSpaceUpdate {
	_u.mutation.SetSpaceID(id)
	return _u
}

// SetSpace sets the "space" edge to the Space entity.
func (_u *LeaseSpaceUpdate) SetSpace(v *Space) *LeaseSpaceUpdate {
	return _u.SetSpaceID(v.ID)
}

// Mutation returns the LeaseSpaceMutation object of the builder.
func (_u *LeaseSpaceUpdate) Mutation() *LeaseSpaceMutation {
	return _u.mutation
}

// ClearLease clears the "lease" edge to the Lease entity.
func (_u *LeaseSpaceUpdate) ClearLease() *LeaseSpaceUpdate {
	_u.mutation.ClearLease()
	return _u
}

// ClearSpace clears the "space" edge to the Space entity.
func (_u *LeaseSpaceUpdate) ClearSpace() *LeaseSpaceUpdate {
	_u.mutation.ClearSpace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LeaseSpaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeaseSpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LeaseSpaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeaseSpaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LeaseSpaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := leasespace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LeaseSpaceUpdate) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := leasespace.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := leasespace.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := leasespace.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relationship(); ok {
		if err := leasespace.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.relationship": %w`, err)}
		}
	}
	if _u.mutation.LeaseCleared() && len(_u.mutation.LeaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaseSpace.lease"`)
	}
	if _u.mutation.SpaceCleared() && len(_u.mutation.SpaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaseSpace.space"`)
	}
	return nil
}

func (_u *LeaseSpaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(leasespace.Table, leasespace.Columns, sqlgraph.NewFieldSpec(leasespace.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(leasespace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(leasespace.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(leasespace.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(leasespace.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(leasespace.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(leasespace.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(leasespace.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(leasespace.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(leasespace.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Relationship(); ok {
		_spec.SetField(leasespace.FieldRelationship, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effective(); ok {
		_spec.SetField(leasespace.FieldEffective, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SquareFootageLeased(); ok {
		_spec.SetField(leasespace.FieldSquareFootageLeased, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSquareFootageLeased(); ok {
		_spec.AddField(leasespace.FieldSquareFootageLeased, field.TypeFloat64, value)
	}
	if _u.mutation.SquareFootageLeasedCleared() {
		_spec.ClearField(leasespace.FieldSquareFootageLeased, field.TypeFloat64)
	}
	if _u.mutation.LeaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.LeaseTable,
			Columns: []string{leasespace.LeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.LeaseTable,
			Columns: []string{leasespace.LeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SpaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.SpaceTable,
			Columns: []string{leasespace.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.SpaceTable,
			Columns: []string{leasespace.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leasespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LeaseSpaceUpdateOne is the builder for updating a single LeaseSpace entity.
type LeaseSpaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LeaseSpaceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LeaseSpaceUpdateOne) SetUpdatedAt(v time.Time) *LeaseSpaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LeaseSpaceUpdateOne) SetCreatedBy(v string) *LeaseSpaceUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableCreatedBy(v *string) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *LeaseSpaceUpdateOne) SetUpdatedBy(v string) *LeaseSpaceUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableUpdatedBy(v *string) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *LeaseSpaceUpdateOne) SetSource(v leasespace.Source) *LeaseSpaceUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableSource(v *leasespace.Source) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *LeaseSpaceUpdateOne) SetCorrelationID(v string) *LeaseSpaceUpdateOne {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableCorrelationID(v *string) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *LeaseSpaceUpdateOne) ClearCorrelationID() *LeaseSpaceUpdateOne {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *LeaseSpaceUpdateOne) SetAgentGoalID(v string) *LeaseSpaceUpdateOne {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableAgentGoalID(v *string) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *LeaseSpaceUpdateOne) ClearAgentGoalID() *LeaseSpaceUpdateOne {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *LeaseSpaceUpdateOne) SetIsPrimary(v bool) *LeaseSpaceUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableIsPrimary(v *bool) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetRelationship sets the "relationship" field.
func (_u *LeaseSpaceUpdateOne) SetRelationship(v leasespace.Relationship) *LeaseSpaceUpdateOne {
	_u.mutation.SetRelationship(v)
	return _u
}

// SetNillableRelationship sets the "relationship" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableRelationship(v *leasespace.Relationship) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetRelationship(*v)
	}
	return _u
}

// SetEffective sets the "effective" field.
func (_u *LeaseSpaceUpdateOne) SetEffective(v *types.DateRange) *LeaseSpaceUpdateOne {
	_u.mutation.SetEffective(v)
	return _u
}

// SetSquareFootageLeased sets the "square_footage_leased" field.
func (_u *LeaseSpaceUpdateOne) SetSquareFootageLeased(v float64) *LeaseSpaceUpdateOne {
	_u.mutation.ResetSquareFootageLeased()
	_u.mutation.SetSquareFootageLeased(v)
	return _u
}

// SetNillableSquareFootageLeased sets the "square_footage_leased" field if the given value is not nil.
func (_u *LeaseSpaceUpdateOne) SetNillableSquareFootageLeased(v *float64) *LeaseSpaceUpdateOne {
	if v != nil {
		_u.SetSquareFootageLeased(*v)
	}
	return _u
}

// AddSquareFootageLeased adds value to the "square_footage_leased" field.
func (_u *LeaseSpaceUpdateOne) AddSquareFootageLeased(v float64) *LeaseSpaceUpdateOne {
	_u.mutation.AddSquareFootageLeased(v)
	return _u
}

// ClearSquareFootageLeased clears the value of the "square_footage_leased" field.
func (_u *LeaseSpaceUpdateOne) ClearSquareFootageLeased() *LeaseSpaceUpdateOne {
	_u.mutation.ClearSquareFootageLeased()
	return _u
}

// SetLeaseID sets the "lease" edge to the Lease entity by ID.
func (_u *LeaseSpaceUpdateOne) SetLeaseID(id uuid.UUID) *LeaseSpaceUpdateOne {
	_u.mutation.SetLeaseID(id)
	return _u
}

// SetLease sets the "lease" edge to the Lease entity.
func (_u *LeaseSpaceUpdateOne) SetLease(v *Lease) *LeaseSpaceUpdateOne {
	return _u.SetLeaseID(v.ID)
}

// SetSpaceID sets the "space" edge to the Space entity by ID.
func (_u *LeaseSpaceUpdateOne) SetSpaceID(id uuid.UUID) *LeaseSpaceUpdateOne {
	_u.mutation.SetSpaceID(id)
	return _u
}

// SetSpace sets the "space" edge to the Space entity.
func (_u *LeaseSpaceUpdateOne) SetSpace(v *Space) *LeaseSpaceUpdateOne {
	return _u.SetSpaceID(v.ID)
}

// Mutation returns the LeaseSpaceMutation object of the builder.
func (_u *LeaseSpaceUpdateOne) Mutation() *LeaseSpaceMutation {
	return _u.mutation
}

// ClearLease clears the "lease" edge to the Lease entity.
func (_u *LeaseSpaceUpdateOne) ClearLease() *LeaseSpaceUpdateOne {
	_u.mutation.ClearLease()
	return _u
}

// ClearSpace clears the "space" edge to the Space entity.
func (_u *LeaseSpaceUpdateOne) ClearSpace() *LeaseSpaceUpdateOne {
	_u.mutation.ClearSpace()
	return _u
}

// Where appends a list predicates to the LeaseSpaceUpdate builder.
func (_u *LeaseSpaceUpdateOne) Where(ps ...predicate.LeaseSpace) *LeaseSpaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LeaseSpaceUpdateOne) Select(field string, fields ...string) *LeaseSpaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LeaseSpace entity.
func (_u *LeaseSpaceUpdateOne) Save(ctx context.Context) (*LeaseSpace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeaseSpaceUpdateOne) SaveX(ctx context.Context) *LeaseSpace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LeaseSpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeaseSpaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LeaseSpaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := leasespace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LeaseSpaceUpdateOne) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := leasespace.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := leasespace.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := leasespace.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relationship(); ok {
		if err := leasespace.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`ent: validator failed for field "LeaseSpace.relationship": %w`, err)}
		}
	}
	if _u.mutation.LeaseCleared() && len(_u.mutation.LeaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaseSpace.lease"`)
	}
	if _u.mutation.SpaceCleared() && len(_u.mutation.SpaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaseSpace.space"`)
	}
	return nil
}

func (_u *LeaseSpaceUpdateOne) sqlSave(ctx context.Context) (_node *LeaseSpace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(leasespace.Table, leasespace.Columns, sqlgraph.NewFieldSpec(leasespace.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LeaseSpace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, leasespace.FieldID)
		for _, f := range fields {
			if !leasespace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != leasespace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(leasespace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(leasespace.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(leasespace.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(leasespace.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(leasespace.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(leasespace.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(leasespace.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(leasespace.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(leasespace.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Relationship(); ok {
		_spec.SetField(leasespace.FieldRelationship, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effective(); ok {
		_spec.SetField(leasespace.FieldEffective, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SquareFootageLeased(); ok {
		_spec.SetField(leasespace.FieldSquareFootageLeased, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSquareFootageLeased(); ok {
		_spec.AddField(leasespace.FieldSquareFootageLeased, field.TypeFloat64, value)
	}
	if _u.mutation.SquareFootageLeasedCleared() {
		_spec.ClearField(leasespace.FieldSquareFootageLeased, field.TypeFloat64)
	}
	if _u.mutation.LeaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.LeaseTable,
			Columns: []string{leasespace.LeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.LeaseTable,
			Columns: []string{leasespace.LeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SpaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.SpaceTable,
			Columns: []string{leasespace.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   leasespace.SpaceTable,
			Columns: []string{leasespace.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LeaseSpace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leasespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
