// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/lease"
	"github.com/matthewbaird/ontology/ent/person"
	"github.com/matthewbaird/ontology/ent/personrole"
	"github.com/matthewbaird/ontology/ent/predicate"
	"github.com/matthewbaird/ontology/internal/types"
)

// PersonRoleUpdate is the builder for updating PersonRole entities.
type PersonRoleUpdate struct {
	config
	hooks    []Hook
	mutation *PersonRoleMutation
}

// Where appends a list predicates to the PersonRoleUpdate builder.
func (_u *PersonRoleUpdate) Where(ps ...predicate.PersonRole) *PersonRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PersonRoleUpdate) SetUpdatedAt(v time.Time) *PersonRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PersonRoleUpdate) SetCreatedBy(v string) *PersonRoleUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableCreatedBy(v *string) *PersonRoleUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PersonRoleUpdate) SetUpdatedBy(v string) *PersonRoleUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableUpdatedBy(v *string) *PersonRoleUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *PersonRoleUpdate) SetSource(v personrole.Source) *PersonRoleUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableSource(v *personrole.Source) *PersonRoleUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *PersonRoleUpdate) SetCorrelationID(v string) *PersonRoleUpdate {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableCorrelationID(v *string) *PersonRoleUpdate {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *PersonRoleUpdate) ClearCorrelationID() *PersonRoleUpdate {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *PersonRoleUpdate) SetAgentGoalID(v string) *PersonRoleUpdate {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableAgentGoalID(v *string) *PersonRoleUpdate {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *PersonRoleUpdate) ClearAgentGoalID() *PersonRoleUpdate {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetRoleType sets the "role_type" field.
func (_u *PersonRoleUpdate) SetRoleType(v personrole.RoleType) *PersonRoleUpdate {
	_u.mutation.SetRoleType(v)
	return _u
}

// SetNillableRoleType sets the "role_type" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableRoleType(v *personrole.RoleType) *PersonRoleUpdate {
	if v != nil {
		_u.SetRoleType(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *PersonRoleUpdate) SetScopeType(v personrole.ScopeType) *PersonRoleUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableScopeType(v *personrole.ScopeType) *PersonRoleUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *PersonRoleUpdate) SetScopeID(v string) *PersonRoleUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableScopeID(v *string) *PersonRoleUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PersonRoleUpdate) SetStatus(v personrole.Status) *PersonRoleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PersonRoleUpdate) SetNillableStatus(v *personrole.Status) *PersonRoleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffective sets the "effective" field.
func (_u *PersonRoleUpdate) SetEffective(v *types.DateRange) *PersonRoleUpdate {
	_u.mutation.SetEffective(v)
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *PersonRoleUpdate) SetAttributes(v *types.TenantAttributes) *PersonRoleUpdate {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *PersonRoleUpdate) ClearAttributes() *PersonRoleUpdate {
	_u.mutation.ClearAttributes()
	return _u
}

// AddLeaseIDs adds the "leases" edge to the Lease entity by IDs.
func (_u *PersonRoleUpdate) AddLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdate {
	_u.mutation.AddLeaseIDs(ids...)
	return _u
}

// AddLeases adds the "leases" edges to the Lease entity.
func (_u *PersonRoleUpdate) AddLeases(v ...*Lease) *PersonRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaseIDs(ids...)
}

// AddGuaranteedLeaseIDs adds the "guaranteed_leases" edge to the Lease entity by IDs.
func (_u *PersonRoleUpdate) AddGuaranteedLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdate {
	_u.mutation.AddGuaranteedLeaseIDs(ids...)
	return _u
}

// AddGuaranteedLeases adds the "guaranteed_leases" edges to the Lease entity.
func (_u *PersonRoleUpdate) AddGuaranteedLeases(v ...*Lease) *PersonRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGuaranteedLeaseIDs(ids...)
}

// SetPersonID sets the "person" edge to the Person entity by ID.
func (_u *PersonRoleUpdate) SetPersonID(id uuid.UUID) *PersonRoleUpdate {
	_u.mutation.SetPersonID(id)
	return _u
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *PersonRoleUpdate) SetPerson(v *Person) *PersonRoleUpdate {
	return _u.SetPersonID(v.ID)
}

// Mutation returns the PersonRoleMutation object of the builder.
func (_u *PersonRoleUpdate) Mutation() *PersonRoleMutation {
	return _u.mutation
}

// ClearLeases clears all "leases" edges to the Lease entity.
func (_u *PersonRoleUpdate) ClearLeases() *PersonRoleUpdate {
	_u.mutation.ClearLeases()
	return _u
}

// RemoveLeaseIDs removes the "leases" edge to Lease entities by IDs.
func (_u *PersonRoleUpdate) RemoveLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdate {
	_u.mutation.RemoveLeaseIDs(ids...)
	return _u
}

// RemoveLeases removes "leases" edges to Lease entities.
func (_u *PersonRoleUpdate) RemoveLeases(v ...*Lease) *PersonRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaseIDs(ids...)
}

// ClearGuaranteedLeases clears all "guaranteed_leases" edges to the Lease entity.
func (_u *PersonRoleUpdate) ClearGuaranteedLeases() *PersonRoleUpdate {
	_u.mutation.ClearGuaranteedLeases()
	return _u
}

// RemoveGuaranteedLeaseIDs removes the "guaranteed_leases" edge to Lease entities by IDs.
func (_u *PersonRoleUpdate) RemoveGuaranteedLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdate {
	_u.mutation.RemoveGuaranteedLeaseIDs(ids...)
	return _u
}

// RemoveGuaranteedLeases removes "guaranteed_leases" edges to Lease entities.
func (_u *PersonRoleUpdate) RemoveGuaranteedLeases(v ...*Lease) *PersonRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGuaranteedLeaseIDs(ids...)
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *PersonRoleUpdate) ClearPerson() *PersonRoleUpdate {
	_u.mutation.ClearPerson()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := personrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonRoleUpdate) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := personrole.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "PersonRole.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := personrole.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "PersonRole.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := personrole.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PersonRole.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleType(); ok {
		if err := personrole.RoleTypeValidator(v); err != nil {
			return &ValidationError{Name: "role_type", err: fmt.Errorf(`ent: validator failed for field "PersonRole.role_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := personrole.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "PersonRole.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := personrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PersonRole.status": %w`, err)}
		}
	}
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonRole.person"`)
	}
	return nil
}

func (_u *PersonRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personrole.Table, personrole.Columns, sqlgraph.NewFieldSpec(personrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(personrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(personrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(personrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(personrole.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(personrole.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(personrole.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(personrole.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(personrole.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleType(); ok {
		_spec.SetField(personrole.FieldRoleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(personrole.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(personrole.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(personrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effective(); ok {
		_spec.SetField(personrole.FieldEffective, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(personrole.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(personrole.FieldAttributes, field.TypeJSON)
	}
	if _u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeasesIDs(); len(nodes) > 0 && !_u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GuaranteedLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGuaranteedLeasesIDs(); len(nodes) > 0 && !_u.mutation.GuaranteedLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuaranteedLeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personrole.PersonTable,
			Columns: []string{personrole.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personrole.PersonTable,
			Columns: []string{personrole.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonRoleUpdateOne is the builder for updating a single PersonRole entity.
type PersonRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PersonRoleUpdateOne) SetUpdatedAt(v time.Time) *PersonRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PersonRoleUpdateOne) SetCreatedBy(v string) *PersonRoleUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableCreatedBy(v *string) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PersonRoleUpdateOne) SetUpdatedBy(v string) *PersonRoleUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableUpdatedBy(v *string) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *PersonRoleUpdateOne) SetSource(v personrole.Source) *PersonRoleUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableSource(v *personrole.Source) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCorrelationID sets the "correlation_id" field.
func (_u *PersonRoleUpdateOne) SetCorrelationID(v string) *PersonRoleUpdateOne {
	_u.mutation.SetCorrelationID(v)
	return _u
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableCorrelationID(v *string) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetCorrelationID(*v)
	}
	return _u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (_u *PersonRoleUpdateOne) ClearCorrelationID() *PersonRoleUpdateOne {
	_u.mutation.ClearCorrelationID()
	return _u
}

// SetAgentGoalID sets the "agent_goal_id" field.
func (_u *PersonRoleUpdateOne) SetAgentGoalID(v string) *PersonRoleUpdateOne {
	_u.mutation.SetAgentGoalID(v)
	return _u
}

// SetNillableAgentGoalID sets the "agent_goal_id" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableAgentGoalID(v *string) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetAgentGoalID(*v)
	}
	return _u
}

// ClearAgentGoalID clears the value of the "agent_goal_id" field.
func (_u *PersonRoleUpdateOne) ClearAgentGoalID() *PersonRoleUpdateOne {
	_u.mutation.ClearAgentGoalID()
	return _u
}

// SetRoleType sets the "role_type" field.
func (_u *PersonRoleUpdateOne) SetRoleType(v personrole.RoleType) *PersonRoleUpdateOne {
	_u.mutation.SetRoleType(v)
	return _u
}

// SetNillableRoleType sets the "role_type" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableRoleType(v *personrole.RoleType) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetRoleType(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *PersonRoleUpdateOne) SetScopeType(v personrole.ScopeType) *PersonRoleUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableScopeType(v *personrole.ScopeType) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *PersonRoleUpdateOne) SetScopeID(v string) *PersonRoleUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableScopeID(v *string) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PersonRoleUpdateOne) SetStatus(v personrole.Status) *PersonRoleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PersonRoleUpdateOne) SetNillableStatus(v *personrole.Status) *PersonRoleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffective sets the "effective" field.
func (_u *PersonRoleUpdateOne) SetEffective(v *types.DateRange) *PersonRoleUpdateOne {
	_u.mutation.SetEffective(v)
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *PersonRoleUpdateOne) SetAttributes(v *types.TenantAttributes) *PersonRoleUpdateOne {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *PersonRoleUpdateOne) ClearAttributes() *PersonRoleUpdateOne {
	_u.mutation.ClearAttributes()
	return _u
}

// AddLeaseIDs adds the "leases" edge to the Lease entity by IDs.
func (_u *PersonRoleUpdateOne) AddLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdateOne {
	_u.mutation.AddLeaseIDs(ids...)
	return _u
}

// AddLeases adds the "leases" edges to the Lease entity.
func (_u *PersonRoleUpdateOne) AddLeases(v ...*Lease) *PersonRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaseIDs(ids...)
}

// AddGuaranteedLeaseIDs adds the "guaranteed_leases" edge to the Lease entity by IDs.
func (_u *PersonRoleUpdateOne) AddGuaranteedLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdateOne {
	_u.mutation.AddGuaranteedLeaseIDs(ids...)
	return _u
}

// AddGuaranteedLeases adds the "guaranteed_leases" edges to the Lease entity.
func (_u *PersonRoleUpdateOne) AddGuaranteedLeases(v ...*Lease) *PersonRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGuaranteedLeaseIDs(ids...)
}

// SetPersonID sets the "person" edge to the Person entity by ID.
func (_u *PersonRoleUpdateOne) SetPersonID(id uuid.UUID) *PersonRoleUpdateOne {
	_u.mutation.SetPersonID(id)
	return _u
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *PersonRoleUpdateOne) SetPerson(v *Person) *PersonRoleUpdateOne {
	return _u.SetPersonID(v.ID)
}

// Mutation returns the PersonRoleMutation object of the builder.
func (_u *PersonRoleUpdateOne) Mutation() *PersonRoleMutation {
	return _u.mutation
}

// ClearLeases clears all "leases" edges to the Lease entity.
func (_u *PersonRoleUpdateOne) ClearLeases() *PersonRoleUpdateOne {
	_u.mutation.ClearLeases()
	return _u
}

// RemoveLeaseIDs removes the "leases" edge to Lease entities by IDs.
func (_u *PersonRoleUpdateOne) RemoveLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdateOne {
	_u.mutation.RemoveLeaseIDs(ids...)
	return _u
}

// RemoveLeases removes "leases" edges to Lease entities.
func (_u *PersonRoleUpdateOne) RemoveLeases(v ...*Lease) *PersonRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaseIDs(ids...)
}

// ClearGuaranteedLeases clears all "guaranteed_leases" edges to the Lease entity.
func (_u *PersonRoleUpdateOne) ClearGuaranteedLeases() *PersonRoleUpdateOne {
	_u.mutation.ClearGuaranteedLeases()
	return _u
}

// RemoveGuaranteedLeaseIDs removes the "guaranteed_leases" edge to Lease entities by IDs.
func (_u *PersonRoleUpdateOne) RemoveGuaranteedLeaseIDs(ids ...uuid.UUID) *PersonRoleUpdateOne {
	_u.mutation.RemoveGuaranteedLeaseIDs(ids...)
	return _u
}

// RemoveGuaranteedLeases removes "guaranteed_leases" edges to Lease entities.
func (_u *PersonRoleUpdateOne) RemoveGuaranteedLeases(v ...*Lease) *PersonRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGuaranteedLeaseIDs(ids...)
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *PersonRoleUpdateOne) ClearPerson() *PersonRoleUpdateOne {
	_u.mutation.ClearPerson()
	return _u
}

// Where appends a list predicates to the PersonRoleUpdate builder.
func (_u *PersonRoleUpdateOne) Where(ps ...predicate.PersonRole) *PersonRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonRoleUpdateOne) Select(field string, fields ...string) *PersonRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PersonRole entity.
func (_u *PersonRoleUpdateOne) Save(ctx context.Context) (*PersonRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonRoleUpdateOne) SaveX(ctx context.Context) *PersonRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := personrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonRoleUpdateOne) check() error {
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := personrole.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "PersonRole.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := personrole.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "PersonRole.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := personrole.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PersonRole.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleType(); ok {
		if err := personrole.RoleTypeValidator(v); err != nil {
			return &ValidationError{Name: "role_type", err: fmt.Errorf(`ent: validator failed for field "PersonRole.role_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := personrole.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "PersonRole.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := personrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PersonRole.status": %w`, err)}
		}
	}
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonRole.person"`)
	}
	return nil
}

func (_u *PersonRoleUpdateOne) sqlSave(ctx context.Context) (_node *PersonRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personrole.Table, personrole.Columns, sqlgraph.NewFieldSpec(personrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personrole.FieldID)
		for _, f := range fields {
			if !personrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(personrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(personrole.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(personrole.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(personrole.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CorrelationID(); ok {
		_spec.SetField(personrole.FieldCorrelationID, field.TypeString, value)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(personrole.FieldCorrelationID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentGoalID(); ok {
		_spec.SetField(personrole.FieldAgentGoalID, field.TypeString, value)
	}
	if _u.mutation.AgentGoalIDCleared() {
		_spec.ClearField(personrole.FieldAgentGoalID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleType(); ok {
		_spec.SetField(personrole.FieldRoleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(personrole.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(personrole.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(personrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Effective(); ok {
		_spec.SetField(personrole.FieldEffective, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(personrole.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(personrole.FieldAttributes, field.TypeJSON)
	}
	if _u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeasesIDs(); len(nodes) > 0 && !_u.mutation.LeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.LeasesTable,
			Columns: personrole.LeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GuaranteedLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGuaranteedLeasesIDs(); len(nodes) > 0 && !_u.mutation.GuaranteedLeasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuaranteedLeasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personrole.GuaranteedLeasesTable,
			Columns: personrole.GuaranteedLeasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lease.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personrole.PersonTable,
			Columns: []string{personrole.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personrole.PersonTable,
			Columns: []string{personrole.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PersonRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
