// Code generated by ent, DO NOT EDIT.

package property

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/matthewbaird/ontology/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedBy, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCorrelationID, v))
}

// AgentGoalID applies equality check predicate on the "agent_goal_id" field. It's identical to AgentGoalIDEQ.
func AgentGoalID(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAgentGoalID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldName, v))
}

// YearBuilt applies equality check predicate on the "year_built" field. It's identical to YearBuiltEQ.
func YearBuilt(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldYearBuilt, v))
}

// TotalSquareFootage applies equality check predicate on the "total_square_footage" field. It's identical to TotalSquareFootageEQ.
func TotalSquareFootage(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTotalSquareFootage, v))
}

// TotalSpaces applies equality check predicate on the "total_spaces" field. It's identical to TotalSpacesEQ.
func TotalSpaces(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTotalSpaces, v))
}

// LotSizeSqft applies equality check predicate on the "lot_size_sqft" field. It's identical to LotSizeSqftEQ.
func LotSizeSqft(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLotSizeSqft, v))
}

// Stories applies equality check predicate on the "stories" field. It's identical to StoriesEQ.
func Stories(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldStories, v))
}

// ParkingSpaces applies equality check predicate on the "parking_spaces" field. It's identical to ParkingSpacesEQ.
func ParkingSpaces(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldParkingSpaces, v))
}

// JurisdictionID applies equality check predicate on the "jurisdiction_id" field. It's identical to JurisdictionIDEQ.
func JurisdictionID(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldJurisdictionID, v))
}

// RentControlled applies equality check predicate on the "rent_controlled" field. It's identical to RentControlledEQ.
func RentControlled(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRentControlled, v))
}

// RequiresLeadDisclosure applies equality check predicate on the "requires_lead_disclosure" field. It's identical to RequiresLeadDisclosureEQ.
func RequiresLeadDisclosure(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRequiresLeadDisclosure, v))
}

// ChartOfAccountsID applies equality check predicate on the "chart_of_accounts_id" field. It's identical to ChartOfAccountsIDEQ.
func ChartOfAccountsID(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldChartOfAccountsID, v))
}

// InsurancePolicyNumber applies equality check predicate on the "insurance_policy_number" field. It's identical to InsurancePolicyNumberEQ.
func InsurancePolicyNumber(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldInsurancePolicyNumber, v))
}

// InsuranceExpiry applies equality check predicate on the "insurance_expiry" field. It's identical to InsuranceExpiryEQ.
func InsuranceExpiry(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldInsuranceExpiry, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldSource, vs...))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldCorrelationID, v))
}

// AgentGoalIDEQ applies the EQ predicate on the "agent_goal_id" field.
func AgentGoalIDEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAgentGoalID, v))
}

// AgentGoalIDNEQ applies the NEQ predicate on the "agent_goal_id" field.
func AgentGoalIDNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldAgentGoalID, v))
}

// AgentGoalIDIn applies the In predicate on the "agent_goal_id" field.
func AgentGoalIDIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDNotIn applies the NotIn predicate on the "agent_goal_id" field.
func AgentGoalIDNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldAgentGoalID, vs...))
}

// AgentGoalIDGT applies the GT predicate on the "agent_goal_id" field.
func AgentGoalIDGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldAgentGoalID, v))
}

// AgentGoalIDGTE applies the GTE predicate on the "agent_goal_id" field.
func AgentGoalIDGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldAgentGoalID, v))
}

// AgentGoalIDLT applies the LT predicate on the "agent_goal_id" field.
func AgentGoalIDLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldAgentGoalID, v))
}

// AgentGoalIDLTE applies the LTE predicate on the "agent_goal_id" field.
func AgentGoalIDLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldAgentGoalID, v))
}

// AgentGoalIDContains applies the Contains predicate on the "agent_goal_id" field.
func AgentGoalIDContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldAgentGoalID, v))
}

// AgentGoalIDHasPrefix applies the HasPrefix predicate on the "agent_goal_id" field.
func AgentGoalIDHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldAgentGoalID, v))
}

// AgentGoalIDHasSuffix applies the HasSuffix predicate on the "agent_goal_id" field.
func AgentGoalIDHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldAgentGoalID, v))
}

// AgentGoalIDIsNil applies the IsNil predicate on the "agent_goal_id" field.
func AgentGoalIDIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldAgentGoalID))
}

// AgentGoalIDNotNil applies the NotNil predicate on the "agent_goal_id" field.
func AgentGoalIDNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldAgentGoalID))
}

// AgentGoalIDEqualFold applies the EqualFold predicate on the "agent_goal_id" field.
func AgentGoalIDEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldAgentGoalID, v))
}

// AgentGoalIDContainsFold applies the ContainsFold predicate on the "agent_goal_id" field.
func AgentGoalIDContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldAgentGoalID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldName, v))
}

// PropertyTypeEQ applies the EQ predicate on the "property_type" field.
func PropertyTypeEQ(v PropertyType) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldPropertyType, v))
}

// PropertyTypeNEQ applies the NEQ predicate on the "property_type" field.
func PropertyTypeNEQ(v PropertyType) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldPropertyType, v))
}

// PropertyTypeIn applies the In predicate on the "property_type" field.
func PropertyTypeIn(vs ...PropertyType) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldPropertyType, vs...))
}

// PropertyTypeNotIn applies the NotIn predicate on the "property_type" field.
func PropertyTypeNotIn(vs ...PropertyType) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldPropertyType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldStatus, vs...))
}

// YearBuiltEQ applies the EQ predicate on the "year_built" field.
func YearBuiltEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldYearBuilt, v))
}

// YearBuiltNEQ applies the NEQ predicate on the "year_built" field.
func YearBuiltNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldYearBuilt, v))
}

// YearBuiltIn applies the In predicate on the "year_built" field.
func YearBuiltIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldYearBuilt, vs...))
}

// YearBuiltNotIn applies the NotIn predicate on the "year_built" field.
func YearBuiltNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldYearBuilt, vs...))
}

// YearBuiltGT applies the GT predicate on the "year_built" field.
func YearBuiltGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldYearBuilt, v))
}

// YearBuiltGTE applies the GTE predicate on the "year_built" field.
func YearBuiltGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldYearBuilt, v))
}

// YearBuiltLT applies the LT predicate on the "year_built" field.
func YearBuiltLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldYearBuilt, v))
}

// YearBuiltLTE applies the LTE predicate on the "year_built" field.
func YearBuiltLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldYearBuilt, v))
}

// TotalSquareFootageEQ applies the EQ predicate on the "total_square_footage" field.
func TotalSquareFootageEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTotalSquareFootage, v))
}

// TotalSquareFootageNEQ applies the NEQ predicate on the "total_square_footage" field.
func TotalSquareFootageNEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldTotalSquareFootage, v))
}

// TotalSquareFootageIn applies the In predicate on the "total_square_footage" field.
func TotalSquareFootageIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldTotalSquareFootage, vs...))
}

// TotalSquareFootageNotIn applies the NotIn predicate on the "total_square_footage" field.
func TotalSquareFootageNotIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldTotalSquareFootage, vs...))
}

// TotalSquareFootageGT applies the GT predicate on the "total_square_footage" field.
func TotalSquareFootageGT(v float64) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldTotalSquareFootage, v))
}

// TotalSquareFootageGTE applies the GTE predicate on the "total_square_footage" field.
func TotalSquareFootageGTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldTotalSquareFootage, v))
}

// TotalSquareFootageLT applies the LT predicate on the "total_square_footage" field.
func TotalSquareFootageLT(v float64) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldTotalSquareFootage, v))
}

// TotalSquareFootageLTE applies the LTE predicate on the "total_square_footage" field.
func TotalSquareFootageLTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldTotalSquareFootage, v))
}

// TotalSpacesEQ applies the EQ predicate on the "total_spaces" field.
func TotalSpacesEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTotalSpaces, v))
}

// TotalSpacesNEQ applies the NEQ predicate on the "total_spaces" field.
func TotalSpacesNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldTotalSpaces, v))
}

// TotalSpacesIn applies the In predicate on the "total_spaces" field.
func TotalSpacesIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldTotalSpaces, vs...))
}

// TotalSpacesNotIn applies the NotIn predicate on the "total_spaces" field.
func TotalSpacesNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldTotalSpaces, vs...))
}

// TotalSpacesGT applies the GT predicate on the "total_spaces" field.
func TotalSpacesGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldTotalSpaces, v))
}

// TotalSpacesGTE applies the GTE predicate on the "total_spaces" field.
func TotalSpacesGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldTotalSpaces, v))
}

// TotalSpacesLT applies the LT predicate on the "total_spaces" field.
func TotalSpacesLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldTotalSpaces, v))
}

// TotalSpacesLTE applies the LTE predicate on the "total_spaces" field.
func TotalSpacesLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldTotalSpaces, v))
}

// LotSizeSqftEQ applies the EQ predicate on the "lot_size_sqft" field.
func LotSizeSqftEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLotSizeSqft, v))
}

// LotSizeSqftNEQ applies the NEQ predicate on the "lot_size_sqft" field.
func LotSizeSqftNEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldLotSizeSqft, v))
}

// LotSizeSqftIn applies the In predicate on the "lot_size_sqft" field.
func LotSizeSqftIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldLotSizeSqft, vs...))
}

// LotSizeSqftNotIn applies the NotIn predicate on the "lot_size_sqft" field.
func LotSizeSqftNotIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldLotSizeSqft, vs...))
}

// LotSizeSqftGT applies the GT predicate on the "lot_size_sqft" field.
func LotSizeSqftGT(v float64) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldLotSizeSqft, v))
}

// LotSizeSqftGTE applies the GTE predicate on the "lot_size_sqft" field.
func LotSizeSqftGTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldLotSizeSqft, v))
}

// LotSizeSqftLT applies the LT predicate on the "lot_size_sqft" field.
func LotSizeSqftLT(v float64) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldLotSizeSqft, v))
}

// LotSizeSqftLTE applies the LTE predicate on the "lot_size_sqft" field.
func LotSizeSqftLTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldLotSizeSqft, v))
}

// LotSizeSqftIsNil applies the IsNil predicate on the "lot_size_sqft" field.
func LotSizeSqftIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldLotSizeSqft))
}

// LotSizeSqftNotNil applies the NotNil predicate on the "lot_size_sqft" field.
func LotSizeSqftNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldLotSizeSqft))
}

// StoriesEQ applies the EQ predicate on the "stories" field.
func StoriesEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldStories, v))
}

// StoriesNEQ applies the NEQ predicate on the "stories" field.
func StoriesNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldStories, v))
}

// StoriesIn applies the In predicate on the "stories" field.
func StoriesIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldStories, vs...))
}

// StoriesNotIn applies the NotIn predicate on the "stories" field.
func StoriesNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldStories, vs...))
}

// StoriesGT applies the GT predicate on the "stories" field.
func StoriesGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldStories, v))
}

// StoriesGTE applies the GTE predicate on the "stories" field.
func StoriesGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldStories, v))
}

// StoriesLT applies the LT predicate on the "stories" field.
func StoriesLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldStories, v))
}

// StoriesLTE applies the LTE predicate on the "stories" field.
func StoriesLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldStories, v))
}

// StoriesIsNil applies the IsNil predicate on the "stories" field.
func StoriesIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldStories))
}

// StoriesNotNil applies the NotNil predicate on the "stories" field.
func StoriesNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldStories))
}

// ParkingSpacesEQ applies the EQ predicate on the "parking_spaces" field.
func ParkingSpacesEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldParkingSpaces, v))
}

// ParkingSpacesNEQ applies the NEQ predicate on the "parking_spaces" field.
func ParkingSpacesNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldParkingSpaces, v))
}

// ParkingSpacesIn applies the In predicate on the "parking_spaces" field.
func ParkingSpacesIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldParkingSpaces, vs...))
}

// ParkingSpacesNotIn applies the NotIn predicate on the "parking_spaces" field.
func ParkingSpacesNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldParkingSpaces, vs...))
}

// ParkingSpacesGT applies the GT predicate on the "parking_spaces" field.
func ParkingSpacesGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldParkingSpaces, v))
}

// ParkingSpacesGTE applies the GTE predicate on the "parking_spaces" field.
func ParkingSpacesGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldParkingSpaces, v))
}

// ParkingSpacesLT applies the LT predicate on the "parking_spaces" field.
func ParkingSpacesLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldParkingSpaces, v))
}

// ParkingSpacesLTE applies the LTE predicate on the "parking_spaces" field.
func ParkingSpacesLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldParkingSpaces, v))
}

// ParkingSpacesIsNil applies the IsNil predicate on the "parking_spaces" field.
func ParkingSpacesIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldParkingSpaces))
}

// ParkingSpacesNotNil applies the NotNil predicate on the "parking_spaces" field.
func ParkingSpacesNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldParkingSpaces))
}

// JurisdictionIDEQ applies the EQ predicate on the "jurisdiction_id" field.
func JurisdictionIDEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldJurisdictionID, v))
}

// JurisdictionIDNEQ applies the NEQ predicate on the "jurisdiction_id" field.
func JurisdictionIDNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldJurisdictionID, v))
}

// JurisdictionIDIn applies the In predicate on the "jurisdiction_id" field.
func JurisdictionIDIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldJurisdictionID, vs...))
}

// JurisdictionIDNotIn applies the NotIn predicate on the "jurisdiction_id" field.
func JurisdictionIDNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldJurisdictionID, vs...))
}

// JurisdictionIDGT applies the GT predicate on the "jurisdiction_id" field.
func JurisdictionIDGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldJurisdictionID, v))
}

// JurisdictionIDGTE applies the GTE predicate on the "jurisdiction_id" field.
func JurisdictionIDGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldJurisdictionID, v))
}

// JurisdictionIDLT applies the LT predicate on the "jurisdiction_id" field.
func JurisdictionIDLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldJurisdictionID, v))
}

// JurisdictionIDLTE applies the LTE predicate on the "jurisdiction_id" field.
func JurisdictionIDLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldJurisdictionID, v))
}

// JurisdictionIDContains applies the Contains predicate on the "jurisdiction_id" field.
func JurisdictionIDContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldJurisdictionID, v))
}

// JurisdictionIDHasPrefix applies the HasPrefix predicate on the "jurisdiction_id" field.
func JurisdictionIDHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldJurisdictionID, v))
}

// JurisdictionIDHasSuffix applies the HasSuffix predicate on the "jurisdiction_id" field.
func JurisdictionIDHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldJurisdictionID, v))
}

// JurisdictionIDIsNil applies the IsNil predicate on the "jurisdiction_id" field.
func JurisdictionIDIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldJurisdictionID))
}

// JurisdictionIDNotNil applies the NotNil predicate on the "jurisdiction_id" field.
func JurisdictionIDNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldJurisdictionID))
}

// JurisdictionIDEqualFold applies the EqualFold predicate on the "jurisdiction_id" field.
func JurisdictionIDEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldJurisdictionID, v))
}

// JurisdictionIDContainsFold applies the ContainsFold predicate on the "jurisdiction_id" field.
func JurisdictionIDContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldJurisdictionID, v))
}

// RentControlledEQ applies the EQ predicate on the "rent_controlled" field.
func RentControlledEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRentControlled, v))
}

// RentControlledNEQ applies the NEQ predicate on the "rent_controlled" field.
func RentControlledNEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldRentControlled, v))
}

// ComplianceProgramsIsNil applies the IsNil predicate on the "compliance_programs" field.
func ComplianceProgramsIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldCompliancePrograms))
}

// ComplianceProgramsNotNil applies the NotNil predicate on the "compliance_programs" field.
func ComplianceProgramsNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldCompliancePrograms))
}

// RequiresLeadDisclosureEQ applies the EQ predicate on the "requires_lead_disclosure" field.
func RequiresLeadDisclosureEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRequiresLeadDisclosure, v))
}

// RequiresLeadDisclosureNEQ applies the NEQ predicate on the "requires_lead_disclosure" field.
func RequiresLeadDisclosureNEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldRequiresLeadDisclosure, v))
}

// ChartOfAccountsIDEQ applies the EQ predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDNEQ applies the NEQ predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDIn applies the In predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldChartOfAccountsID, vs...))
}

// ChartOfAccountsIDNotIn applies the NotIn predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldChartOfAccountsID, vs...))
}

// ChartOfAccountsIDGT applies the GT predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDGTE applies the GTE predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDLT applies the LT predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDLTE applies the LTE predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDContains applies the Contains predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDHasPrefix applies the HasPrefix predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDHasSuffix applies the HasSuffix predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDIsNil applies the IsNil predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldChartOfAccountsID))
}

// ChartOfAccountsIDNotNil applies the NotNil predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldChartOfAccountsID))
}

// ChartOfAccountsIDEqualFold applies the EqualFold predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldChartOfAccountsID, v))
}

// ChartOfAccountsIDContainsFold applies the ContainsFold predicate on the "chart_of_accounts_id" field.
func ChartOfAccountsIDContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldChartOfAccountsID, v))
}

// InsurancePolicyNumberEQ applies the EQ predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberNEQ applies the NEQ predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberIn applies the In predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldInsurancePolicyNumber, vs...))
}

// InsurancePolicyNumberNotIn applies the NotIn predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldInsurancePolicyNumber, vs...))
}

// InsurancePolicyNumberGT applies the GT predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberGTE applies the GTE predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberLT applies the LT predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberLTE applies the LTE predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberContains applies the Contains predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberHasPrefix applies the HasPrefix predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberHasSuffix applies the HasSuffix predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberIsNil applies the IsNil predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldInsurancePolicyNumber))
}

// InsurancePolicyNumberNotNil applies the NotNil predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldInsurancePolicyNumber))
}

// InsurancePolicyNumberEqualFold applies the EqualFold predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldInsurancePolicyNumber, v))
}

// InsurancePolicyNumberContainsFold applies the ContainsFold predicate on the "insurance_policy_number" field.
func InsurancePolicyNumberContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldInsurancePolicyNumber, v))
}

// InsuranceExpiryEQ applies the EQ predicate on the "insurance_expiry" field.
func InsuranceExpiryEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldInsuranceExpiry, v))
}

// InsuranceExpiryNEQ applies the NEQ predicate on the "insurance_expiry" field.
func InsuranceExpiryNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldInsuranceExpiry, v))
}

// InsuranceExpiryIn applies the In predicate on the "insurance_expiry" field.
func InsuranceExpiryIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldInsuranceExpiry, vs...))
}

// InsuranceExpiryNotIn applies the NotIn predicate on the "insurance_expiry" field.
func InsuranceExpiryNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldInsuranceExpiry, vs...))
}

// InsuranceExpiryGT applies the GT predicate on the "insurance_expiry" field.
func InsuranceExpiryGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldInsuranceExpiry, v))
}

// InsuranceExpiryGTE applies the GTE predicate on the "insurance_expiry" field.
func InsuranceExpiryGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldInsuranceExpiry, v))
}

// InsuranceExpiryLT applies the LT predicate on the "insurance_expiry" field.
func InsuranceExpiryLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldInsuranceExpiry, v))
}

// InsuranceExpiryLTE applies the LTE predicate on the "insurance_expiry" field.
func InsuranceExpiryLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldInsuranceExpiry, v))
}

// InsuranceExpiryIsNil applies the IsNil predicate on the "insurance_expiry" field.
func InsuranceExpiryIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldInsuranceExpiry))
}

// InsuranceExpiryNotNil applies the NotNil predicate on the "insurance_expiry" field.
func InsuranceExpiryNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldInsuranceExpiry))
}

// HasPortfolio applies the HasEdge predicate on the "portfolio" edge.
func HasPortfolio() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PortfolioTable, PortfolioColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPortfolioWith applies the HasEdge predicate on the "portfolio" edge with a given conditions (other predicates).
func HasPortfolioWith(preds ...predicate.Portfolio) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newPortfolioStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBuildings applies the HasEdge predicate on the "buildings" edge.
func HasBuildings() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BuildingsTable, BuildingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBuildingsWith applies the HasEdge predicate on the "buildings" edge with a given conditions (other predicates).
func HasBuildingsWith(preds ...predicate.Building) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newBuildingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSpaces applies the HasEdge predicate on the "spaces" edge.
func HasSpaces() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SpacesTable, SpacesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpacesWith applies the HasEdge predicate on the "spaces" edge with a given conditions (other predicates).
func HasSpacesWith(preds ...predicate.Space) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newSpacesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBankAccount applies the HasEdge predicate on the "bank_account" edge.
func HasBankAccount() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, BankAccountTable, BankAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBankAccountWith applies the HasEdge predicate on the "bank_account" edge with a given conditions (other predicates).
func HasBankAccountWith(preds ...predicate.BankAccount) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newBankAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplications applies the HasEdge predicate on the "applications" edge.
func HasApplications() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ApplicationsTable, ApplicationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationsWith applies the HasEdge predicate on the "applications" edge with a given conditions (other predicates).
func HasApplicationsWith(preds ...predicate.Application) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newApplicationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerEntries applies the HasEdge predicate on the "ledger_entries" edge.
func HasLedgerEntries() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerEntriesWith applies the HasEdge predicate on the "ledger_entries" edge with a given conditions (other predicates).
func HasLedgerEntriesWith(preds ...predicate.LedgerEntry) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newLedgerEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPropertyJurisdictions applies the HasEdge predicate on the "property_jurisdictions" edge.
func HasPropertyJurisdictions() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PropertyJurisdictionsTable, PropertyJurisdictionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyJurisdictionsWith applies the HasEdge predicate on the "property_jurisdictions" edge with a given conditions (other predicates).
func HasPropertyJurisdictionsWith(preds ...predicate.PropertyJurisdiction) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newPropertyJurisdictionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Property) predicate.Property {
	return predicate.Property(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Property) predicate.Property {
	return predicate.Property(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Property) predicate.Property {
	return predicate.Property(sql.NotPredicates(p))
}
